/**
 * Iceland Inc.: the players and the instruments that connect them.
 *
 * Ten players in seven groups, as in engine v1: three household age groups, domestic-market
 * firms, exporters, the banks (as one), the central bank, the government, the pension funds and
 * the rest of the world. Fifteen instruments: thirteen financial claims (someone's asset and
 * someone else's liability) and two real assets, homes and firms' capital.
 */
import type { ModuleDef } from '../../../core/types.ts';

export const structure: ModuleDef = {
  id: 'structure',
  label: 'Players and instruments',
  description: 'Households by age, two kinds of firm, banks, the central bank, the government, pension funds and the rest of the world, with the claims between them.',
  players: [
    {
      id: 'HY',
      label: 'Young households (18–34)',
      short: 'Young',
      group: 'Households',
      color: '#8FC3E8',
      description: 'People aged 18 to 34 and their children. They work, rent or buy their first home with a mortgage, and swing most in and out of jobs.',
      settlement: 'deposits',
      layout: { x: 0.12, y: 0.4 },
    },
    {
      id: 'HW',
      label: 'Working-age households (35–66)',
      short: 'Working age',
      group: 'Households',
      color: '#3A87C8',
      description: 'People aged 35 to 66. They earn most of the wages, carry most of the mortgage debt, own most small businesses and build up pension rights.',
      settlement: 'deposits',
      layout: { x: 0.12, y: 0.55 },
    },
    {
      id: 'HO',
      label: 'Older households (67+)',
      short: 'Older',
      group: 'Households',
      color: '#1B4B82',
      description: 'People aged 67 and over. They live on pensions and savings, own their homes outright and sell homes to younger people.',
      settlement: 'deposits',
      layout: { x: 0.12, y: 0.7 },
    },
    {
      id: 'FD',
      label: 'Domestic-market firms',
      short: 'Domestic firms',
      group: 'Firms',
      color: '#F2A93B',
      description: 'Shops, services and builders selling at home. They import most of the goods households buy, pay VAT and borrow from banks.',
      settlement: 'deposits',
      layout: { x: 0.85, y: 0.47 },
    },
    {
      id: 'FX',
      label: 'Exporters',
      short: 'Exporters',
      group: 'Firms',
      color: '#C8611A',
      description: 'Fishing, aluminium smelting, tourism and other exports. They earn foreign currency and part of their profit goes to foreign owners.',
      settlement: 'deposits',
      layout: { x: 0.85, y: 0.64 },
    },
    {
      id: 'B',
      label: 'Banks',
      short: 'Banks',
      group: 'Banks',
      color: '#009E73',
      description: 'All commercial banks as one. They keep everyone’s deposits, lend to households and firms, and hold government bonds and reserves.',
      settlement: 'bank',
      layout: { x: 0.38, y: 0.9 },
    },
    {
      id: 'CB',
      label: 'Central bank',
      short: 'Central bank',
      group: 'Central bank',
      color: '#CC79A7',
      description: 'Seðlabanki Íslands. It sets the key rate, pays interest on banks’ reserves, holds the foreign-exchange reserves and keeps the government’s account.',
      settlement: 'central-bank',
      layout: { x: 0.15, y: 0.1 },
    },
    {
      id: 'G',
      label: 'Government',
      short: 'Government',
      group: 'Government',
      color: '#B5A300',
      description: 'State and municipalities. They run health, education and other services, pay transfers, collect taxes and borrow by selling bonds.',
      settlement: 'treasury',
      layout: { x: 0.5, y: 0.1 },
    },
    {
      id: 'PF',
      label: 'Pension funds',
      short: 'Pension funds',
      group: 'Pension funds',
      color: '#882255',
      description: 'The funded pension system, worth about 180% of GDP. Funds collect contributions, pay pensions, lend mortgages and invest at home and abroad.',
      settlement: 'deposits',
      layout: { x: 0.64, y: 0.9 },
    },
    {
      id: 'W',
      label: 'Rest of world',
      short: 'Abroad',
      group: 'Rest of world',
      color: '#8C8C8C',
      description: 'Everyone outside Iceland: buyers of exports, sellers of imports, tourists, foreign owners, and investors holding krónur.',
      settlement: 'deposits',
      layout: { x: 0.85, y: 0.1 },
    },
  ],
  instruments: [
    {
      id: 'deposits',
      label: 'Bank deposits',
      kind: 'financial',
      issuers: ['B'],
      holders: ['HY', 'HW', 'HO', 'FD', 'FX', 'PF', 'W'],
      valuation: 'nominal',
      description: 'Money as most people know it: a claim on the banks. Created when banks lend, buy bonds or pay; destroyed when they are repaid.',
      concepts: ['endogenous-money', 'broad-money'],
    },
    {
      id: 'reserves',
      label: 'Central-bank reserves',
      kind: 'financial',
      issuers: ['CB'],
      holders: ['B'],
      valuation: 'nominal',
      description: 'Banks’ accounts at the central bank. Every payment between the private sector and the state moves reserves.',
      concepts: ['reserves-and-payments'],
    },
    {
      id: 'treasuryAccount',
      label: 'Treasury account',
      kind: 'financial',
      issuers: ['CB'],
      holders: ['G'],
      valuation: 'nominal',
      description: 'The government’s account at the central bank: taxes arrive here and spending leaves from here.',
      concepts: ['reserves-and-payments'],
    },
    {
      id: 'mortgagesN',
      label: 'Mortgages, non-indexed',
      kind: 'financial',
      issuers: ['HY', 'HW'],
      holders: ['B', 'PF'],
      valuation: 'nominal',
      description: 'Home loans at a floating nominal rate that follows the key rate. Lent by banks and pension funds.',
      concepts: ['amortisation', 'interest-distribution'],
    },
    {
      id: 'mortgagesI',
      label: 'Mortgages, CPI-indexed',
      kind: 'financial',
      issuers: ['HY', 'HW'],
      holders: ['B', 'PF'],
      valuation: 'cpi-indexed',
      description: 'Home loans whose principal grows with the consumer price index; the borrower pays a low real rate in cash. About 65% of Icelandic mortgages.',
      concepts: ['indexation', 'accrual-vs-cash'],
    },
    {
      id: 'businessLoans',
      label: 'Business loans',
      kind: 'financial',
      issuers: ['FD', 'FX'],
      holders: ['B'],
      valuation: 'nominal',
      description: 'What firms owe the banks. Firms borrow to keep enough cash on hand; each new loan creates a deposit.',
      concepts: ['endogenous-money', 'money-destruction'],
    },
    {
      id: 'govBonds',
      label: 'Government bonds',
      kind: 'financial',
      issuers: ['G'],
      holders: ['B', 'CB', 'PF', 'HO', 'W'],
      valuation: 'nominal',
      description: 'Floating-rate government bonds, held by banks, the central bank, pension funds, older savers and foreign carry traders.',
      concepts: ['deficits-and-money', 'bond-buyers'],
    },
    {
      id: 'indexedBonds',
      label: 'Government bonds, CPI-indexed',
      kind: 'financial',
      issuers: ['G'],
      holders: ['PF'],
      valuation: 'cpi-indexed',
      description: 'Government bonds whose principal grows with the CPI, held by pension funds. Indexation adds to the debt without any cash moving.',
      concepts: ['indexation'],
    },
    {
      id: 'bankBonds',
      label: 'Bank bonds',
      kind: 'financial',
      issuers: ['B'],
      holders: ['PF'],
      valuation: 'nominal',
      description: 'Covered bonds the banks sell to pension funds. When a fund buys one, its deposit is cancelled, so broad money shrinks.',
      concepts: ['broad-money'],
    },
    {
      id: 'shares',
      label: 'Company shares (book value)',
      kind: 'financial',
      issuers: ['FD', 'FX'],
      holders: ['HY', 'HW', 'HO', 'PF', 'W'],
      valuation: 'at-cost',
      description: 'Ownership of firms at book value. Held constant, as in v1: the owners’ income arrives as dividends, set by fixed payout shares.',
      concepts: ['net-worth'],
    },
    {
      id: 'fxReserves',
      label: 'Foreign-exchange reserves',
      kind: 'financial',
      issuers: ['W'],
      holders: ['CB'],
      valuation: 'fx',
      description: 'The central bank’s foreign assets, worth more krónur when the króna weakens.',
      concepts: ['revaluation', 'floating-exchange-rate'],
    },
    {
      id: 'foreignAssets',
      label: 'Pension funds’ foreign assets',
      kind: 'financial',
      issuers: ['W'],
      holders: ['PF'],
      valuation: 'fx',
      description: 'Foreign shares and bonds held by pension funds, about 42% of their assets. Buying them means selling krónur.',
      concepts: ['revaluation', 'funded-pensions'],
    },
    {
      id: 'pensionRights',
      label: 'Pension rights',
      kind: 'financial',
      issuers: ['PF'],
      holders: ['HW', 'HO'],
      valuation: 'nominal',
      description: 'What pension funds owe their members. Contributions and credited returns add to them; pensions paid use them up.',
      concepts: ['pension-entitlements', 'funded-pensions'],
    },
    {
      id: 'homes',
      label: 'Homes',
      kind: 'real',
      issuers: [],
      holders: ['HY', 'HW', 'HO'],
      valuation: 'price-index',
      description: 'Owner-occupied homes at market value. Younger households buy them from older ones; their value moves with house prices.',
      concepts: ['intergenerational-flows', 'housing-wealth-effect'],
    },
    {
      id: 'capital',
      label: 'Machines and buildings',
      kind: 'real',
      issuers: [],
      holders: ['FD', 'FX'],
      valuation: 'at-cost',
      description: 'Firms’ capital, valued at what it cost. Investment adds to it and wear and tear reduces it. New in the port: v1 counted investment as spending.',
      concepts: ['net-worth'],
    },
  ],
};
