/**
 * Markdown report for one model: summary, the six layers, and the published baseline
 * (balance-sheet matrix, transactions-flow matrix, every variable).
 */
import { ROLE_ISSUER } from '../core/compile.ts';
import type { HarnessResult } from './layers.ts';

const num = (x: number, d = 2) => {
  if (!Number.isFinite(x)) return String(x);
  const v = Math.abs(x) < 0.5 * 10 ** -d ? 0 : x;
  return v.toFixed(d);
};

export function renderReport(r: HarnessResult): string {
  const L: string[] = [];
  L.push(`# Harness report: ${r.label} (\`${r.modelId}\`)`, '');
  L.push(`Generated by \`bun run harness\`. Overall: **${r.pass ? 'PASS' : 'FAIL'}**.`, '');
  L.push('| # | Layer | Result | Summary |', '|---|---|---|---|');
  for (const l of r.layers) L.push(`| ${l.n} | ${l.title} | ${l.pass ? 'PASS' : '**FAIL**'} | ${l.summary} |`);
  const tm = r.timing;
  // The step time depends on the machine and its load, so it is printed by `bun run harness` and
  // kept out of the committed report, which then changes only when results do.
  L.push('', `Step time: printed by \`bun run harness\`, not stored here since it depends on the machine${tm ? ` (the mean over ${tm.runs} runs of ${tm.months} months, each from ${tm.shock} at month 0; up to ${tm.maxIterations} solver iteration(s) in a month)` : ''}.`, '');
  for (const l of r.layers) {
    L.push(`## ${l.n}. ${l.title}: ${l.pass ? 'PASS' : 'FAIL'}`, '');
    L.push(...l.body, '');
  }
  const m = r.model,
    b = r.baseline;
  if (m && b) {
    L.push('## Appendix: the published baseline', '');
    L.push('Units: flows in % of baseline annual GDP at annual rates; stocks in % of baseline GDP; rates as fractions per year; prices as indices.', '');
    const solved = Object.entries(b.solved);
    if (solved.length) L.push(`Solved parameters: ${solved.map(([k, v]) => `\`${k}\` = ${num(v, 6)}`).join(', ')}.`, '');
    // balance-sheet matrix
    L.push('### Balance-sheet matrix (assets +, liabilities −)', '');
    L.push(`| Instrument | ${m.players.map((p) => p.id).join(' | ')} | Sum |`, `|---|${m.players.map(() => '---:').join('|')}|---:|`);
    const nw = new Array(m.NP).fill(0);
    m.instruments.forEach((ins, i) => {
      let s = 0;
      const cells = m.players.map((_, p) => {
        const j = i * m.NP + p;
        if (!m.role[j]) return '';
        const v = b.stocks.find((x) => x.instrument === ins.id && x.player === m.players[p].id)!.value * (m.role[j] === ROLE_ISSUER ? -1 : 1);
        s += v;
        nw[p] += v;
        return num(v);
      });
      L.push(`| ${ins.label} | ${cells.join(' | ')} | ${num(s)} |`);
    });
    L.push(`| **Net worth** | ${nw.map((v) => `**${num(v)}**`).join(' | ')} | **${num(nw.reduce((a, c) => a + c, 0))}** |`, '');
    // transactions-flow matrix
    L.push('### Transactions-flow matrix (receipts +, payments −; annual rates)', '');
    L.push(`| Flow | Kind | ${m.players.map((p) => p.id).join(' | ')} | Sum |`, `|---|---|${m.players.map(() => '---:').join('|')}|---:|`);
    m.flows.forEach((fl) => {
      const row = new Array(m.NP).fill(0);
      const within = new Array(m.NP).fill(0); // flows inside one sector (firms buying from firms)
      for (const leg of b.legs.filter((x) => x.flow === fl.id)) {
        const from = m.playerIndex.get(leg.from)!,
          to = m.playerIndex.get(leg.to)!;
        if (from === to && (fl.kind === 'revaluation' || fl.kind === 'writeoff')) {
          row[from] += fl.kind === 'writeoff' ? -leg.value : leg.value;
          continue;
        }
        if (from === to) within[from] += leg.value;
        row[from] -= leg.value;
        row[to] += leg.value;
      }
      const cell = (p: number) => (within[p] ? `±${num(within[p])}` : row[p] ? num(row[p]) : '');
      L.push(`| ${fl.label} | ${fl.kind} | ${m.players.map((_, p) => cell(p)).join(' | ')} | ${num(row.reduce((a, c) => a + c, 0))} |`);
    });
    L.push('', 'A ± entry is paid and received inside one sector, such as firms buying machines from other firms.', '');
    // variables
    L.push('### Variables', '', '| Variable | Label | Value | Unit |', '|---|---|---:|---|');
    for (const v of m.vars) L.push(`| \`${v.id}\` | ${v.label} | ${num(b.vars[v.id], 6)} | ${v.unit} |`);
    L.push('');
  }
  return L.join('\n');
}
