/* ---------------------------------------------------------------- 20_structure.js
 * Sectors (10 Godley columns), instruments (13) and transaction rows (with explain texts).
 */
var HY = 0, HW = 1, HO = 2, FD = 3, FX = 4, B = 5, CB = 6, G = 7, PF = 8, W = 9, NS = 10;
var DEP = 0, RES = 1, TGA = 2, MN = 3, MI = 4, LOAN = 5, BOND = 6, BONDI = 7, BBOND = 8, EQ = 9, FXR = 10, FA = 11, PEN = 12, NI = 13;
var IS_DEP = [1, 1, 1, 1, 1, 0, 0, 0, 1, 1];   // holds a bank deposit account (pays and is paid in deposits)

// Colour-blind-safe: one hue family per group (blue, orange, green, purple, olive, wine, grey), lightness steps inside.
var SECTORS = [
  { id: 'HY', label: 'Young households (18-34)', group: 'Households', color: '#8FC3E8' },
  { id: 'HW', label: 'Working-age households (35-66)', group: 'Households', color: '#3A87C8' },
  { id: 'HO', label: 'Older households (67+)', group: 'Households', color: '#1B4B82' },
  { id: 'FD', label: 'Domestic-market firms', group: 'Firms', color: '#F2A93B' },
  { id: 'FX', label: 'Exporters (fish, aluminium, tourism)', group: 'Firms', color: '#C8611A' },
  { id: 'B', label: 'Banks', group: 'Banks', color: '#009E73' },
  { id: 'CB', label: 'Central bank', group: 'Central bank', color: '#CC79A7' },
  { id: 'G', label: 'Government', group: 'Government', color: '#B5A300' },
  { id: 'PF', label: 'Pension funds', group: 'Pension funds', color: '#882255' },
  { id: 'W', label: 'Rest of world', group: 'Rest of world', color: '#8C8C8C' }
];
var INSTRUMENTS = [
  { id: 'dep', label: 'Bank deposits' }, { id: 'res', label: 'Central bank reserves' },
  { id: 'tga', label: 'Treasury account at the central bank' }, { id: 'mortN', label: 'Mortgages, non-indexed' },
  { id: 'mortI', label: 'Mortgages, CPI-indexed' }, { id: 'loan', label: 'Business loans' },
  { id: 'bond', label: 'Government bonds' }, { id: 'bondI', label: 'Government bonds, CPI-indexed' },
  { id: 'bbond', label: 'Bank bonds' }, { id: 'eq', label: 'Company shares (book value)' },
  { id: 'fxr', label: 'Foreign-exchange reserves' }, { id: 'fa', label: 'Foreign assets of pension funds' },
  { id: 'pen', label: 'Pension rights' }
];

// Transaction rows. type: current|capital (enter saving) | financial (swap assets) | other (revaluation, no saving).
// Each row: id, label, type, kind, channel?, category, what, rule, params (ids for explain()).
function R_(id, label, type, kind, category, what, rule, params, channel) {
  return { id: id, label: label, type: type, kind: kind, category: category, what: what, rule: rule, params: params || [], channel: channel };
}
var ROWS = [
  R_('cons', 'Household consumption', 'current', 'cash', 'BEHAVIOUR',
    'Households buy goods and services, including VAT, from domestic firms. Imported goods reach them through those firms.',
    'Each age group moves its spending gradually toward a target: C* = MPC x (labour and transfer income after tax and mortgage interest, plus home sales minus home purchases) + a low MPC x real interest and dividends, damped by the real key rate, + a share of liquid wealth, of new borrowing and of housing-wealth gains.',
    ['aLY', 'aLW', 'aLO', 'aK', 'betaC', 'aWY', 'aWW', 'aWO', 'aNL', 'aHO', 'lamC']),
  R_('vat', 'VAT and taxes on goods', 'current', 'cash', 'POLICY',
    'Firms pass the VAT they collect on consumer spending to the government.', 'VAT = v / (1 + v) x consumer spending, v = effective VAT rate (lever).', ['vat0', 'vatTarget']),
  R_('g_health', 'Public health services', 'current', 'cash', 'POLICY',
    'The government runs hospitals and clinics: it pays staff wages (and their pension contributions) and buys supplies from domestic firms.',
    'Spending = real level (lever) x [wage share x wage index + (1 - wage share) x domestic price]. Staff wages go to households by age; pension contributions go to pension funds.',
    ['gHealth', 'wsHealth', 'cEr', 'cEe'], 'health'),
  R_('g_edu', 'Public education', 'current', 'cash', 'POLICY',
    'Schools and universities: teachers\' wages and pension contributions, plus purchases from domestic firms.',
    'Same rule as health, with its own level and wage share.', ['gEdu', 'wsEdu'], 'education'),
  R_('g_other', 'Other public services', 'current', 'cash', 'POLICY',
    'Administration, police, culture, road upkeep and subsidies: wages plus purchases from domestic firms.',
    'Same rule as health, with its own level and wage share.', ['gOther', 'wsOther'], 'other'),
  R_('g_inv', 'Public investment', 'current', 'cash', 'POLICY',
    'The government buys roads, buildings and equipment from domestic firms (who import part of it).',
    'Spending = real level (lever) x domestic price.', ['gInv'], 'investment'),
  R_('inv', 'Business investment', 'current', 'cash', 'BEHAVIOUR',
    'Exporters buy machines and buildings from domestic firms. Domestic firms\' own investment stays inside that sector.',
    'Investment moves (with a planning lag) toward: baseline x [1 + {betaPi} x (profits / baseline - 1) - {betaRI} x (real loan rate - baseline) + {betaU} x output gap].',
    ['iFD0', 'iFX0', 'betaPi', 'betaRI', 'betaU', 'lamInv']),
  R_('inputs', 'Exporters\' domestic inputs', 'current', 'cash', 'BEHAVIOUR',
    'Exporters buy food, transport, energy and services from domestic firms (hotels buy food, smelters buy services).',
    'Inputs = fixed amount per unit of exports x domestic price.', ['muXD', 'vaFXtarget']),
  R_('exports', 'Exports', 'current', 'cash', 'BEHAVIOUR',
    'Foreigners pay exporters for fish, aluminium, tourism and other services.',
    'Volume = baseline x foreign demand (or tourism lever) x (real exchange rate)^elasticity. Fish and aluminium are priced in foreign currency, so a weaker krona raises their krona value at once.',
    ['xFish', 'xAlu', 'xTour', 'xOther', 'eFish', 'eAlu', 'eTour', 'eOther']),
  R_('imports', 'Imports', 'current', 'cash', 'BEHAVIOUR',
    'Firms pay foreigners for imported consumer goods, inputs, machinery, and the alumina and fuel exporters use.',
    'Imports = {muC%} of consumption + {muD%} of other domestic sales + {muI%} of investment + {muG%} of public purchases + {muX%} of exports; home-market imports scale with (real exchange rate)^-{epsM}.',
    ['muC', 'muD', 'muI', 'muX', 'epsM']),
  R_('wages', 'Wages (private sector)', 'current', 'cash', 'BEHAVIOUR',
    'Firms pay wages to households. Shown net of the employee pension contribution, which goes straight to pension funds.',
    'Wage bill = wage rate x employment. Employment follows sector output with a lag; young workers\' jobs swing most.',
    ['okun', 'lamN', 'cycY', 'cycW', 'cycO', 'mig']),
  R_('pencon', 'Pension contributions (private employers)', 'current', 'cash', 'CONTRACT',
    'Firms pay the employer and employee pension contributions to pension funds.',
    'Contributions = (employer {cEr%} + employee {cEe%}) x gross wages. Wages are counted once: the employee part is deducted from the wage row, the employer part is paid on top.',
    ['cEr', 'cEe', 'conTarget']),
  R_('paytax', 'Payroll tax', 'current', 'cash', 'POLICY', 'Firms pay the social security tax on wages to the government.', 'Payroll tax = {css%} x gross private wages.', ['css']),
  R_('inctax', 'Personal income tax', 'current', 'cash', 'POLICY',
    'Households pay income tax on wages, benefits and pensions.',
    'Tax = rate x taxable income; rate = {tau0%} + lever + debt-tied rule ({phiTau} x debt/GDP gap, phased in at {lamTau} per year). Also stands in for other taxes on households.',
    ['tau0', 'phiTau', 'lamTau']),
  R_('corptax', 'Corporate income tax', 'current', 'cash', 'POLICY', 'Firms pay tax on their profits.', 'Tax = effective rate x profit after interest (effective rate set so baseline revenue matches the data).', ['tauF', 'citTarget']),
  R_('ben_oa', 'Old-age and disability transfers', 'current', 'cash', 'POLICY',
    'Social Insurance pays public pensions (mostly to the old) and disability benefits (mostly working age).',
    'Transfers = real level (lever) x CPI, split by age group.', ['trOA', 'oaShareO', 'oaShareY'], 'oldAge'),
  R_('ben_fam', 'Family and housing benefits', 'current', 'cash', 'POLICY',
    'Child benefits, parental leave and housing support, paid to young and working-age families.',
    'Transfers = real level (lever) x CPI, split by age group.', ['trFam', 'famShareY'], 'family'),
  R_('ben_ue', 'Unemployment benefits', 'current', 'cash', 'POLICY',
    'Paid automatically to the unemployed in each age group.', 'Benefits = replacement rate x wage per worker x unemployed persons.', ['rr'], 'unemployment'),
  R_('penpay', 'Pension payouts', 'current', 'cash', 'CONTRACT',
    'Pension funds pay pensions to retired households.', 'Payouts = {payout} x pensioners\' pension rights per year.', ['payout']),
  R_('int_dep', 'Interest on deposits', 'current', 'cash', 'BEHAVIOUR', 'Banks pay interest to depositors.', 'Deposit rate = key rate - {mD pp}.', ['mD']),
  R_('int_res', 'Interest on reserves', 'current', 'cash', 'POLICY', 'The central bank pays the key rate on banks\' reserves.', 'Interest = key rate x reserves.', []),
  R_('int_mort', 'Mortgage interest (cash)', 'current', 'cash', 'CONTRACT',
    'Borrowers pay interest to banks and pension funds.',
    'Non-indexed: (key rate + {sMN pp} + capital premium) x debt. Indexed: real rate ({rMI0%} at baseline, moves {psiIdx} x the key rate) x debt; the inflation part is added to the loan instead (see indexation).',
    ['sMN', 'rMI0', 'psiIdx', 'sCap']),
  R_('int_loan', 'Interest on business loans', 'current', 'cash', 'BEHAVIOUR', 'Firms pay interest to banks.', 'Rate = key rate + {sL pp} + capital premium.', ['sL', 'sCap']),
  R_('int_bond', 'Interest on government bonds', 'current', 'cash', 'CONTRACT',
    'The government pays interest to bondholders: banks, the central bank, pension funds, older households and foreigners.', 'Floating rate = key rate + {sB pp}.', ['sB']),
  R_('int_bondI', 'Real coupon on indexed bonds', 'current', 'cash', 'CONTRACT', 'The government pays the real coupon on indexed bonds (held by pension funds).', 'Coupon = {rBI0%} x indexed principal.', ['rBI0']),
  R_('int_bbond', 'Interest on bank bonds', 'current', 'cash', 'CONTRACT', 'Banks pay interest on the covered bonds pension funds hold.', 'Rate = key rate + {sBB pp}.', ['sBB']),
  R_('int_fxr', 'Income on FX reserves', 'current', 'cash', 'BEHAVIOUR', 'Foreign assets of the central bank earn interest.', 'Income = foreign yield x reserves (krona value).', ['iFXR']),
  R_('int_fa', 'Income on pension funds\' foreign assets', 'current', 'cash', 'BEHAVIOUR', 'Dividends and interest from pension funds\' foreign portfolio.', 'Income = foreign yield x foreign assets (krona value).', ['iF0']),
  R_('div', 'Dividends and owners\' income', 'current', 'cash', 'BEHAVIOUR',
    'Firms and banks pay out profits: to households (including self-employed and owners\' income), pension funds, the government (bank shares) and foreign owners (aluminium).',
    'Firms pay out (1 - retention) x after-tax profit; retention rises with debt. Banks pay smoothed profit minus what they need to rebuild capital.',
    ['rhoFD0', 'rhoFX0', 'rhoL', 'lamEq', 'lamDivB', 'divFDW', 'divFDO', 'divFXW', 'divBshG', 'divBshPF']),
  R_('cbrem', 'Central bank profit to government', 'current', 'cash', 'POLICY', 'The central bank hands its profit to the government.', 'Remittance = interest earned - interest paid on reserves.', []),
  R_('idx_mort', 'Mortgage indexation (accrued)', 'current', 'accrual', 'CONTRACT',
    'On CPI-indexed loans, inflation is added to the loan balance instead of being paid in cash. No money moves.',
    'Indexation = indexed debt x monthly CPI change; capitalised into principal.', ['theta']),
  R_('idx_bond', 'Government bond indexation (accrued)', 'current', 'accrual', 'CONTRACT',
    'Inflation is added to the principal of indexed government bonds held by pension funds. No money moves.',
    'Indexation = indexed debt x monthly CPI change.', ['govIdxShare']),
  R_('penadj', 'Pension rights: earned minus used (accrued)', 'current', 'accrual', 'CONTRACT',
    'Contributions give working-age members new pension rights; paying a pension uses up pensioners\' rights. No money moves in this row.',
    'Working age +contributions; old -payouts; pension funds the difference.', ['cEr', 'cEe', 'payout']),
  R_('penret', 'Returns credited to pension rights', 'current', 'accrual', 'BEHAVIOUR',
    'Pension funds credit their investment income (and, slowly, gains and losses) to members\' rights.',
    'Credited = smoothed fund income + {lamPFnw} x (fund surplus - target surplus), shared by rights held.', ['lamPFinc', 'lamPFnw']),
  R_('homes', 'Purchases of existing homes', 'capital', 'cash', 'BEHAVIOUR',
    'Young and working-age households buy homes from older households, who sell to downsize or as estates are settled. The buyer\'s money becomes the seller\'s deposit.',
    'Value = house price x a fixed number of homes changing hands per year.', ['purY', 'purW']),
  R_('mort_new', 'New mortgages', 'financial', 'cash', 'BEHAVIOUR',
    'Banks and pension funds lend to home buyers. A bank loan creates a new deposit (new money); a pension-fund loan moves the fund\'s existing deposits.',
    'Lending = repayments + {lamM} x (desired debt - debt) + lending-appetite lever, capped by the debt-service rule (payments at stress rates {floorN%}/{termN} yrs non-indexed and {floorI%}/{termI} yrs indexed <= {dstiY%} of income for the young, {dstiW%} for others) and an optional LTV cap. Desired debt = ratio x income x (1 - {betaM} x real-rate change) x (real house price)^{betaMH}.',
    ['mRY', 'mRW', 'lamM', 'betaM', 'betaMH', 'dstiY', 'dstiW', 'floorN', 'termN', 'floorI', 'termI']),
  R_('mort_rep', 'Mortgage repayments', 'financial', 'cash', 'CONTRACT',
    'Borrowers pay down principal. Repaying a bank loan destroys the deposit used.', 'Repayment = debt / {Tm} years, per year.', ['Tm']),
  R_('loans', 'Business borrowing (net)', 'financial', 'cash', 'IDENTITY',
    'Firms borrow from banks (or repay) to keep enough cash on hand; bank loans create deposits.', 'Net borrowing = target deposits (share of GDP) - deposits after this month\'s flows.', []),
  R_('bond_iss', 'New government bonds', 'financial', 'cash', 'POLICY',
    'The government borrows its deficit by selling bonds. If banks or the central bank buy, new money is created; if pension funds or households buy, existing money moves.',
    'Issuance = the month\'s cash deficit, split among buyers by the lever.', []),
  R_('bond_trade', 'Government bond trading', 'financial', 'cash', 'BEHAVIOUR',
    'Foreign carry traders, pension funds and older savers buy or sell existing bonds, mostly from banks.',
    'Foreigners want more when Icelandic rates exceed foreign rates; pension funds keep a liquidity target; older savers keep a bond share.', ['psiB', 'lamBW', 'lamReb']),
  R_('bbond', 'Bank bond purchases', 'financial', 'cash', 'BEHAVIOUR',
    'Pension funds buy covered bonds from banks. Deposits turn into bank bonds, so broad money shrinks.', 'Moves toward a target share of pension assets.', ['lamReb']),
  R_('fa_buy', 'Pension funds\' foreign investment', 'financial', 'cash', 'BEHAVIOUR',
    'Pension funds sell kronur to buy foreign assets, which pushes the krona down.', 'Moves foreign assets toward the target share ({pfForeignShare}% of assets + lever) at {lamFA} of the gap per year.', ['pfForeignShare', 'lamFA']),
  R_('rev_fxr', 'Revaluation of FX reserves', 'other', 'reval', 'IDENTITY',
    'When the krona weakens, the central bank\'s foreign reserves are worth more kronur. A valuation change, not a payment.', 'Change = reserves x percentage change in the exchange rate.', []),
  R_('rev_fa', 'Revaluation of foreign pension assets', 'other', 'reval', 'IDENTITY',
    'When the krona weakens, pension funds\' foreign assets are worth more kronur. A valuation change, not a payment.', 'Change = foreign assets x percentage change in the exchange rate.', []),
  R_('ageing', 'Retirement: rights move to pensioners', 'other', 'reval', 'IDENTITY',
    'As members retire, their pension rights move from the working-age group to the old. Not a payment: a reclassification between households.',
    'Moved = ageing rate x working-age rights per year.', ['ageing'])
];
var ROW_IX = {}; ROWS.forEach(function (r, j) { ROW_IX[r.id] = j; r.saving = r.type === 'current' || r.type === 'capital'; });
