/**
 * Generates docs/concepts.md, the index of the concept library, from src/concepts/library.ts.
 *
 *   bun run scripts/concepts-index.ts
 *
 * tests/concepts.test.ts checks that the committed index matches this output.
 */
import { writeFileSync } from 'node:fs';
import { conceptById, concepts, conceptThemes } from '../src/concepts/library.ts';

export const INDEX_PATH = new URL('../docs/concepts.md', import.meta.url);

/** Make text safe inside a markdown table cell. */
const cell = (text: string): string => text.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ');

export function renderConceptIndex(): string {
  const lines: string[] = [
    '# Concept library',
    '',
    '<!-- Generated by `bun run scripts/concepts-index.ts` from `src/concepts/library.ts`. Do not edit by hand. -->',
    '',
    `The ${concepts.length} economic ideas that Iceland Inc. can show as "at play" when you click a flow, a player or an indicator. ` +
      'Rules, terms, flows, levers and indicators refer to them by id. Each entry in `src/concepts/library.ts` also has a ' +
      'plain-English explanation, references and related ideas.',
    '',
  ];
  for (const { theme, ids } of conceptThemes) {
    lines.push(`## ${theme}`, '', '| Id | Title | One-liner | School |', '|---|---|---|---|');
    for (const id of ids) {
      const c = conceptById.get(id);
      if (!c) throw new Error(`Theme "${theme}" lists unknown concept "${id}"`);
      lines.push(`| \`${c.id}\` | ${cell(c.title)} | ${cell(c.oneLiner)} | ${c.school} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

if (import.meta.main) {
  const text = renderConceptIndex();
  writeFileSync(INDEX_PATH, text);
  console.log(`Wrote ${INDEX_PATH.pathname} (${concepts.length} concepts)`);
}
