/**
 * Iceland Inc.: what theory predicts for each lever. Each entry is the sign of a lever's mean
 * effect on a headline or indicator over a span of months, against the no-change run in the same
 * lock configuration (src/harness/lever-report.ts, LeverExpectation): 'unlocked', the default, where
 * the central bank's rule and the debt rule act; 'locked', where both policy levers are held (the
 * old Manual setting); and 'key rate locked', where only the key rate is held. Moving a policy
 * lever locks it, so its own runs hold it in every configuration (decision 0010). The lever report (bun run levers) marks
 * each one ✓ or ✗, and the harness (bun run harness, robustness layer) fails when one does not
 * hold. Most come from the lever vetting of 29 September 2026 (docs/audit/lever-vetting.md), where
 * economists proposed robust signs that any sound model should show; the rest pin the signs the
 * fixes after that vetting restored. Expectations the model cannot meet yet are not here: the
 * vetting record lists them as open problems, and those judged too strong for this model as
 * dropped, each with the reason.
 *
 * Checks that are not signs (the cash limit never binding, households keeping a quarter of their
 * deposits, every firm's loans staying below three times their normal share of GDP) cannot be
 * written here, since the report measures only headlines and indicators; they are model tests in
 * tests/models/iceland-real-economy.test.ts.
 */
import type { LeverExpectation } from '../../harness/lever-report.ts';

export const expectations: LeverExpectation[] = [
  // ------------------------------------------------ the key rate held, income tax held too (locked)
  { lever: 'keyRate', setting: 'up', mode: 'locked', variable: 'output', fromMonth: 6, toMonth: 36, sign: -1, theory: 'Interest-rate channel: a higher real rate lowers consumption and investment, so output falls with a lag of quarters.', source: 'Christiano, Eichenbaum and Evans (2005); CBI QMM v2.1 Monetary Bulletin rate experiment' },
  { lever: 'keyRate', setting: 'up', mode: 'locked', variable: 'inflation', fromMonth: 12, toMonth: 36, sign: -1, theory: 'Slack, a stronger krona and lower asset prices reduce inflation after a lag.', source: 'Havranek and Rusnak (2013); CBI QMM v2.1' },
  { lever: 'keyRate', setting: 'up', mode: 'locked', variable: 'krona', fromMonth: 1, toMonth: 12, sign: 1, theory: 'Uncovered interest parity: a higher domestic rate attracts carry flows and strengthens the currency on impact.', source: 'Dornbusch (1976); CBI QMM v2.1 (0.67% per pp on impact)' },
  { lever: 'keyRate', setting: 'up', mode: 'locked', variable: 'unemployment', fromMonth: 12, toMonth: 36, sign: 1, theory: 'Okun’s law: lower output after tightening raises unemployment.', source: 'Okun (1962); CBI QMM v2.1' },
  { lever: 'keyRate', setting: 'max', mode: 'locked', variable: 'realHousePrice', fromMonth: 6, toMonth: 36, sign: -1, theory: 'Asset-price channel: higher mortgage rates lower what buyers can pay for homes.', source: 'Jarocinski and Smets (2008); Williams (2015), FRBSF' },
  { lever: 'keyRate', setting: 'up', mode: 'locked', variable: 'investment', fromMonth: 6, toMonth: 36, sign: -1, theory: 'User cost of capital: a higher real loan rate lowers desired investment.', source: 'Jorgenson (1963); Christiano, Eichenbaum and Evans (2005)' },
  { lever: 'keyRate', setting: 'min', mode: 'locked', variable: 'inflation', fromMonth: 12, toMonth: 36, sign: 1, theory: 'The mirror of tightening: a lower real rate stimulates demand and weakens the krona, raising inflation after a lag.', source: 'CBI QMM v2.1; Havranek and Rusnak (2013)' },
  { lever: 'keyRate', setting: 'up', mode: 'locked', variable: 'mortgageDebt', fromMonth: 12, toMonth: 60, sign: -1, theory: 'Credit/bank-lending channel: dearer credit slows new borrowing, so the debt ratio falls over years.', source: 'Bernanke and Gertler (1995); Bank of England Quarterly Bulletin 2014 Q1' },
  { lever: 'keyRate', setting: 'up', mode: 'locked', variable: 'investment', fromMonth: 1, toMonth: 24, sign: -1, theory: 'A higher real borrowing cost lowers investment, with a lag.', source: 'Christiano, Eichenbaum and Evans (2005), Journal of Political Economy 113' },
  { lever: 'keyRate', setting: 'up', mode: 'locked', variable: 'output', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Monetary tightening lowers output within two years.', source: 'Christiano, Eichenbaum and Evans (2005), Journal of Political Economy 113' },

  // ------------------------------------ the key rate held, the debt rule acting (unlocked)
  // Until padlocks (decision 0010) these were expectations on an offset added to the rule, which
  // the rule then leaned against; rules can no longer be tilted, so they are now on locking the key
  // rate higher or lower while the debt rule acts. The rule's lean is gone, so the key rate stays
  // where it is set: the keyRate expectation below replaces "the offset raises the key rate on
  // impact, the rule offsets only part of it at first because of smoothing".
  { lever: 'keyRate', setting: 'up', mode: 'unlocked', variable: 'output', fromMonth: 6, toMonth: 36, sign: -1, theory: 'A contractionary monetary stance lowers demand through the interest-rate channel.', source: 'Gali (2015), ch. 3 monetary policy shock; CBI QMM v2.1' },
  { lever: 'keyRate', setting: 'up', mode: 'unlocked', variable: 'inflation', fromMonth: 12, toMonth: 36, sign: -1, theory: 'A tighter stance lowers inflation through slack and the exchange rate.', source: 'Gali (2015); CBI QMM v2.1' },
  { lever: 'keyRate', setting: 'up', mode: 'unlocked', variable: 'keyRate', fromMonth: 1, toMonth: 240, sign: 1, theory: 'Moving the lever locks it: the key rate is held where it is set, above the neutral rate, for as long as it is set.', source: 'Decision 0010 (padlocks); model rule 11' },
  { lever: 'keyRate', setting: 'up', mode: 'unlocked', variable: 'krona', fromMonth: 1, toMonth: 12, sign: 1, theory: 'Uncovered interest parity: a wider rate gap strengthens the krona.', source: 'Dornbusch (1976); CBI QMM v2.1' },
  { lever: 'keyRate', setting: 'up', mode: 'unlocked', variable: 'unemployment', fromMonth: 12, toMonth: 36, sign: 1, theory: 'Okun’s law: tighter policy lowers output and raises unemployment in the medium run.', source: 'Okun (1962); CBI QMM v2.1' },
  { lever: 'keyRate', setting: 'max', mode: 'unlocked', variable: 'realHousePrice', fromMonth: 6, toMonth: 36, sign: -1, theory: 'Asset-price channel: higher mortgage rates lower house prices.', source: 'Jarocinski and Smets (2008)' },
  { lever: 'keyRate', setting: 'down', mode: 'unlocked', variable: 'output', fromMonth: 6, toMonth: 36, sign: 1, theory: 'An expansionary monetary stance raises demand in the medium run.', source: 'Gali (2015); CBI QMM v2.1' },

  // --------------------------------------------------------------------------------- the padlocks
  // They replace the global switch's expectations (a switch from Manual to Automatic with no shock
  // changed nothing): at the steady state each rule's value is its lever's default, so opening or
  // closing a padlock with no shock changes nothing.
  { lever: 'keyRateLock', setting: 0, mode: 'locked', variable: 'output', fromMonth: 1, toMonth: 240, sign: 0, theory: 'At the steady state the rule’s target equals the neutral rate. Handing the key rate back to the rule with no shock changes nothing (decisions 0004 and 0010: the same baseline, locked or not).', source: 'Decisions 0004 and 0010; Taylor (1993): the rule’s rate equals the neutral nominal rate at target inflation and zero gap' },
  { lever: 'keyRateLock', setting: 0, mode: 'locked', variable: 'keyRate', fromMonth: 1, toMonth: 240, sign: 0, theory: 'With no shock, the rule’s suggestion equals the held neutral rate, so unlocking moves no policy instrument.', source: 'Decisions 0004 and 0010; Taylor (1993)' },
  { lever: 'keyRateLock', setting: 0, mode: 'locked', variable: 'inflation', fromMonth: 1, toMonth: 240, sign: 0, theory: 'No shock means no policy reaction, so inflation stays at target, locked or not.', source: 'Decisions 0004 and 0010' },
  { lever: 'incomeTaxLock', setting: 0, mode: 'locked', variable: 'incomeTaxRate', fromMonth: 1, toMonth: 240, sign: 0, theory: 'At the steady state debt is at its baseline ratio, so the debt rule’s shift is zero: handing income tax back to the rule with no shock changes nothing.', source: 'Decisions 0004 and 0010' },
  { lever: 'keyRateLock', setting: 1, mode: 'unlocked', variable: 'keyRate', fromMonth: 1, toMonth: 240, sign: 0, theory: 'Locking with no shock freezes the key rate at the rate in force, the neutral rate, so nothing moves.', source: 'Decision 0010' },
  { lever: 'incomeTaxLock', setting: 1, mode: 'unlocked', variable: 'output', fromMonth: 1, toMonth: 240, sign: 0, theory: 'Locking income tax with no shock freezes it at the rate in force, the baseline rate, so nothing moves.', source: 'Decision 0010' },

  // ------------------------------------------------------------------------------ the króna
  { lever: 'kronaShock', setting: 'min', variable: 'krona', fromMonth: 1, toMonth: 12, sign: -1, theory: 'A sentiment (risk-premium) shock that raises the króna’s target weakens it at once and for most of a year, as in UIP with a risk-premium shock.', source: 'Dornbusch (1976); Central Bank of Iceland QMM risk-premium shock' },
  { lever: 'kronaShock', setting: 'min', variable: 'priceLevel', fromMonth: 3, toMonth: 24, sign: 1, theory: 'Exchange-rate pass-through: a weaker króna makes imports dearer in krónur and the CPI rises.', source: 'Campa and Goldberg (2005); Edwards and Cabezas (2021, Central Bank of Iceland)' },
  { lever: 'kronaShock', setting: 'max', variable: 'priceLevel', fromMonth: 3, toMonth: 24, sign: -1, theory: 'Pass-through works in reverse: a stronger króna lowers import prices and the CPI.', source: 'Campa and Goldberg (2005); Edwards and Cabezas (2021)' },
  { lever: 'kronaShock', setting: 'min', variable: 'realWage', fromMonth: 3, toMonth: 12, sign: -1, theory: 'Prices react before wages, so a depreciation squeezes real wages in the first year.', source: 'Blanchard, Macroeconomics (real-wage effect of depreciation); Central Bank of Iceland Monetary Bulletin' },
  { lever: 'kronaShock', setting: 'min', variable: 'exports', fromMonth: 3, toMonth: 12, sign: 1, theory: 'Expenditure switching: a real depreciation makes Icelandic goods and tourism cheaper abroad.', source: 'Obstfeld and Rogoff (1996)' },
  { lever: 'kronaShock', setting: 'min', variable: 'imports', fromMonth: 3, toMonth: 12, sign: -1, theory: 'Expenditure switching: dearer imports lower import volumes.', source: 'Obstfeld and Rogoff (1996)' },
  { lever: 'kronaShock', setting: 'min', variable: 'currentAccount', fromMonth: 12, toMonth: 36, sign: 1, theory: 'Once volumes have responded, the Marshall-Lerner condition makes the current account improve after a real depreciation (after any initial J-curve dip).', source: 'Magee (1973); Bahmani-Oskooee and Ratha (2004)' },
  { lever: 'kronaShock', setting: 'min', mode: 'unlocked', variable: 'keyRate', fromMonth: 3, toMonth: 24, sign: 1, theory: 'An inflation-targeting rule raises the key rate when depreciation-driven inflation rises.', source: 'Taylor (1993); Svensson (1997)' },

  // ------------------------------------------------------------------------- the foreign rate
  { lever: 'foreignRate', setting: 'max', variable: 'krona', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Uncovered interest parity and the carry trade: a higher foreign rate makes króna assets less attractive, so the króna weakens.', source: 'Dornbusch (1976); Brunnermeier, Nagel and Pedersen (2008)' },
  { lever: 'foreignRate', setting: 'min', variable: 'krona', fromMonth: 1, toMonth: 24, sign: 1, theory: 'UIP in reverse: lower foreign rates draw carry money into krónur and the króna strengthens.', source: 'Dornbusch (1976)' },
  { lever: 'foreignRate', setting: 'max', variable: 'inflation', fromMonth: 3, toMonth: 12, sign: 1, theory: 'The depreciation that follows a foreign rate rise passes through to import prices and the CPI.', source: 'Campa and Goldberg (2005)' },
  { lever: 'foreignRate', setting: 'max', variable: 'exports', fromMonth: 6, toMonth: 24, sign: 1, theory: 'The real depreciation switches foreign demand toward Icelandic goods (Mundell-Fleming).', source: 'Mundell (1963); Fleming (1962)' },
  { lever: 'foreignRate', setting: 'max', variable: 'imports', fromMonth: 6, toMonth: 24, sign: -1, theory: 'The real depreciation makes imports dearer, so import volumes fall.', source: 'Obstfeld and Rogoff (1996)' },
  { lever: 'foreignRate', setting: 'max', mode: 'unlocked', variable: 'keyRate', fromMonth: 6, toMonth: 24, sign: 1, theory: 'An inflation-targeting central bank tightens against imported inflation from the weaker króna.', source: 'Taylor (1993)' },
  { lever: 'foreignRate', setting: 'min', mode: 'unlocked', variable: 'keyRate', fromMonth: 6, toMonth: 24, sign: -1, theory: 'An appreciation lowers inflation and the rule eases.', source: 'Taylor (1993)' },

  // ------------------------------------------------------------------------------ world prices
  { lever: 'importPrices', setting: 'max', variable: 'priceLevel', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Higher foreign-currency prices pass through to import prices in krónur and to the CPI.', source: 'Campa and Goldberg (2005); Edwards and Cabezas (2021)' },
  { lever: 'importPrices', setting: 'up', variable: 'inflation', fromMonth: 1, toMonth: 12, sign: 1, theory: 'Imported inflation: dearer imports raise 12-month CPI inflation.', source: 'Campa and Goldberg (2005)' },
  { lever: 'importPrices', setting: 'down', variable: 'inflation', fromMonth: 1, toMonth: 12, sign: -1, theory: 'Imported disinflation: cheaper imports lower CPI inflation.', source: 'Campa and Goldberg (2005)' },
  { lever: 'importPrices', setting: 'up', variable: 'realWage', fromMonth: 3, toMonth: 12, sign: -1, theory: 'Consumer prices rise before wages catch up, so real wages fall.', source: 'Blanchard, Macroeconomics' },
  { lever: 'importPrices', setting: 'up', variable: 'profitsFX', fromMonth: 1, toMonth: 12, sign: 1, theory: 'Fish and aluminium are priced in foreign currency, so higher world prices raise exporters’ króna revenue against mostly domestic costs.', source: 'Central Bank of Iceland Monetary Bulletin (export sectors); standard export-price income effect' },
  { lever: 'importPrices', setting: 'up', mode: 'unlocked', variable: 'keyRate', fromMonth: 3, toMonth: 24, sign: 1, theory: 'The inflation rule raises the key rate against imported inflation.', source: 'Taylor (1993)' },
  { lever: 'importPrices', setting: 'up', variable: 'krona', fromMonth: 60, toMonth: 240, sign: 1, theory: 'Purchasing-power parity: higher foreign prices lead, over years, to a stronger nominal króna.', source: 'Rogoff (1996); Sarno and Taylor (2002)' },
  { lever: 'importPrices', setting: 'min', variable: 'krona', fromMonth: 60, toMonth: 240, sign: -1, theory: 'PPP in reverse: lower foreign prices lead, over years, to a weaker nominal króna.', source: 'Rogoff (1996); Sarno and Taylor (2002)' },

  // --------------------------------------------------------------------------- foreign demand
  { lever: 'foreignDemand', setting: 'max', variable: 'exports', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Export volumes rise with foreign demand (income elasticity of export demand).', source: 'Houthakker and Magee (1969), Review of Economics and Statistics' },
  { lever: 'foreignDemand', setting: 'max', variable: 'output', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Open-economy Keynesian multiplier: more export demand raises GDP before appreciation crowds it out.', source: 'Mundell (1963); Fleming (1962); Justiniano and Preston (2010), Journal of International Economics 81' },
  { lever: 'foreignDemand', setting: 'max', variable: 'unemployment', fromMonth: 3, toMonth: 24, sign: -1, theory: 'Okun’s law: higher output lowers unemployment.', source: 'Okun (1962); Ball, Leigh and Loungani (2017)' },
  { lever: 'foreignDemand', setting: 'max', variable: 'krona', fromMonth: 6, toMonth: 36, sign: 1, theory: 'Higher export earnings and a current-account surplus strengthen a floating currency (flow and portfolio-balance demand for krónur).', source: 'Kouri (1976); Obstfeld and Rogoff (1996), ch. 9' },
  { lever: 'foreignDemand', setting: 'max', variable: 'currentAccount', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Exports rise faster than the imports they induce, so the current account improves.', source: 'BPM6 current-account identity; Obstfeld and Rogoff (1996)' },
  { lever: 'foreignDemand', setting: 'max', variable: 'jobsXT', fromMonth: 12, toMonth: 60, sign: -1, theory: 'Dutch disease: a boom in one export sector appreciates the real exchange rate and crowds out other tradables such as tourism.', source: 'Corden and Neary (1982), Economic Journal' },
  { lever: 'foreignDemand', setting: 'min', variable: 'output', fromMonth: 1, toMonth: 24, sign: -1, theory: 'A fall in export demand lowers GDP through the multiplier.', source: 'Mundell (1963); Fleming (1962)' },
  { lever: 'foreignDemand', setting: 'up', mode: 'unlocked', variable: 'keyRate', fromMonth: 3, toMonth: 12, sign: 1, theory: 'A Taylor rule raises the policy rate when output rises above capacity.', source: 'Taylor (1993)' },

  // --------------------------------------------------------------------------------- tourism
  { lever: 'tourism', setting: 'min', variable: 'output', fromMonth: 1, toMonth: 36, sign: -1, theory: 'Tourism is an export; losing it lowers GDP (Iceland 2020: tourism about −75%, GDP about −7%).', source: 'Hagstofa national accounts 2020; CBI Monetary Bulletin 2020/4' },
  { lever: 'tourism', setting: 'min', variable: 'unemployment', fromMonth: 3, toMonth: 36, sign: 1, theory: 'Tourism is labour-intensive, so a collapse raises unemployment quickly.', source: 'Hagstofa labour force survey 2020; Okun (1962)' },
  { lever: 'tourism', setting: 'min', variable: 'krona', fromMonth: 3, toMonth: 36, sign: -1, theory: 'Lost export earnings weaken a floating currency (the króna fell about 10% in trade-weighted terms in 2020).', source: 'Landsbankinn, 8 January 2021; CBI Monetary Bulletin 2020/4' },
  { lever: 'tourism', setting: 'min', variable: 'currentAccount', fromMonth: 1, toMonth: 36, sign: -1, theory: 'Lower service exports worsen the current account.', source: 'BPM6; CBI balance of payments 2020' },
  { lever: 'tourism', setting: 'min', mode: 'unlocked', variable: 'keyRate', fromMonth: 3, toMonth: 24, sign: -1, theory: 'A Taylor rule cuts the rate in a demand collapse (the CBI cut from 3% to 0.75% in 2020).', source: 'Taylor (1993); CBI rate decisions 2020' },
  { lever: 'tourism', setting: 'max', variable: 'krona', fromMonth: 6, toMonth: 36, sign: 1, theory: 'A tourism boom brings in foreign currency and appreciates the króna (as in 2013–17).', source: 'CBI Monetary Bulletin 2016–2017; Obstfeld and Rogoff (1996)' },
  { lever: 'tourism', setting: 'max', variable: 'profitsXF', fromMonth: 12, toMonth: 60, sign: -1, theory: 'Dutch disease: the appreciation from a tourism boom cuts króna revenue of exporters priced in foreign currency (fisheries’ margins fell in 2016–17).', source: 'Corden and Neary (1982); Deloitte Sjávarútvegsgagnagrunnur 2016–2017' },
  { lever: 'tourism', setting: 'max', variable: 'output', fromMonth: 1, toMonth: 24, sign: 1, theory: 'More visitors raise output over the following quarters.', source: 'CBI QMM simulations' },
  { lever: 'tourism', setting: 'min', variable: 'output', fromMonth: 1, toMonth: 24, sign: -1, theory: 'A collapse in visitors lowers output at once (2010, 2020).', source: 'Statistics Iceland national accounts, 2020' },
  { lever: 'tourism', setting: 'max', variable: 'krona', fromMonth: 12, toMonth: 240, sign: 1, theory: 'A lasting export gain strengthens the currency in real and nominal terms (Dutch disease).', source: 'Corden and Neary (1982), Economic Journal 92' },
  // Re-specified with decision 0012 (owner decision 10 of the long-run-anchors proposal): it said
  // "inflation over months 180–240 does not move", which catches the upswing of a slow learning cycle.
  // The inflation gap after tourism −15 is about −0.08 pp at month 60, crosses zero near month 180
  // and is +0.02 by month 240, at every strength of the rule tested; its mean over months 180–240 was
  // +0.007 pp with the fixed potential and is +0.015 with the labour-market gap, above the 0.01
  // floor. What theory predicts is that the gap dies out, so that is what is tested: the largest gap
  // over months 180–240 (0.028 pp; 0.018 before) is under 0.05 pp and under half the largest over
  // months 36–96 (0.103; 0.074 before).
  { lever: 'tourism', setting: 'down', mode: 'unlocked', variable: 'inflation', fromMonth: 180, toMonth: 240, sign: 0, decays: { earlier: [36, 96], below: 0.05, share: 0.5 }, theory: 'An inflation-targeting central bank brings inflation back to target after a lasting real shock, once it has learned the new neutral rate: the cycle of its learning dies out.', source: 'Svensson (1997), European Economic Review 41; Laubach and Williams (2003), Review of Economics and Statistics 85(4)' },

  // ------------------------------------------------------------------------------ fish prices
  { lever: 'fishPrices', setting: 'max', variable: 'currentAccount', fromMonth: 1, toMonth: 24, sign: 1, theory: 'A higher world price for a quota-bound export raises export earnings one for one on impact (a terms-of-trade gain).', source: 'Obstfeld and Rogoff (1996), ch. 1; BPM6' },
  { lever: 'fishPrices', setting: 'max', variable: 'profitsXF', fromMonth: 1, toMonth: 60, sign: 1, theory: 'With catches fixed by quotas, a price rise accrues to fisheries as resource rent.', source: 'Arnason (2008), on the Icelandic ITQ system' },
  { lever: 'fishPrices', setting: 'max', variable: 'krona', fromMonth: 3, toMonth: 36, sign: 1, theory: 'Commodity currencies appreciate when the real price of their commodity exports rises.', source: 'Cashin, Céspedes and Sahay (2004), Journal of Development Economics' },
  { lever: 'fishPrices', setting: 'max', variable: 'govBalance', fromMonth: 1, toMonth: 36, sign: 1, theory: 'Higher fisheries’ profits raise corporate tax (and the fishing fee).', source: 'Lög um veiðigjald nr. 145/2018; Hagstofa government finance' },
  { lever: 'fishPrices', setting: 'max', variable: 'realDisposableIncome', fromMonth: 6, toMonth: 36, sign: 1, theory: 'A terms-of-trade gain raises real national income, through cheaper imports after appreciation and through owners’ income.', source: 'Kohli (2004), Review of Income and Wealth; Corden and Neary (1982)' },
  { lever: 'fishPrices', setting: 'max', variable: 'jobsXT', fromMonth: 12, toMonth: 60, sign: -1, theory: 'Dutch disease: a commodity boom appreciates the currency and shrinks other tradables.', source: 'Corden and Neary (1982)' },
  { lever: 'fishPrices', setting: 'min', variable: 'currentAccount', fromMonth: 1, toMonth: 24, sign: -1, theory: 'A terms-of-trade loss on a quota-bound export lowers export earnings.', source: 'Obstfeld and Rogoff (1996); BPM6' },
  { lever: 'fishPrices', setting: 'max', variable: 'output', fromMonth: 1, toMonth: 12, sign: 1, theory: 'The income (spending) effect of a domestically owned commodity windfall comes before the slower expenditure switching from appreciation, so short-run output rises. This holds after fixing trade-fish-windfall-hoarded; it was about 0 at the vetting (−0.02).', source: 'IMF World Economic Outlook, October 2012, ch. 4; Corden and Neary (1982)' },
  { lever: 'fishPrices', setting: 'max', variable: 'profitsFX', fromMonth: 1, toMonth: 60, sign: 1, theory: 'Quotas cap the catch, so a higher price goes mainly into fisheries’ profit (resource rent).', source: 'Arnason (2008) on Iceland’s ITQ fisheries' },
  { lever: 'fishPrices', setting: 'max', mode: 'locked', variable: 'govBalance', fromMonth: 24, toMonth: 60, sign: 1, theory: 'The state takes a share of resource rent through the fishing fee and corporate tax.', source: 'Lög um veiðigjald nr. 145/2018' },
  { lever: 'fishPrices', setting: 'min', variable: 'profitsFX', fromMonth: 1, toMonth: 60, sign: -1, theory: 'A lower price cuts fisheries’ profit, since volume is quota-bound.', source: 'Arnason (2008) on Iceland’s ITQ fisheries' },
  { lever: 'fishPrices', setting: 'min', variable: 'investment', fromMonth: 12, toMonth: 240, sign: -1, theory: 'A squeezed, indebted exporter invests less (cash-flow and leverage constraints on investment).', source: 'Fazzari, Hubbard and Petersen (1988), Brookings Papers 1988:1' },

  // -------------------------------------------------------------------------- aluminium price
  { lever: 'aluminiumPrice', setting: 'max', variable: 'profitsXA', fromMonth: 1, toMonth: 60, sign: 1, theory: 'The smelters run at capacity and sell at the world price, so a price rise raises their profit.', source: 'Hagstofa THJ08420; Landsvirkjun annual reports' },
  { lever: 'aluminiumPrice', setting: 'max', variable: 'dividendsAbroad', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Foreign-owned firms remit windfall profits to their parents as primary income paid abroad.', source: 'Eurostat bop_c6_a (Iceland inward FDI income); BPM6 ch. 11' },
  { lever: 'aluminiumPrice', setting: 'max', variable: 'currentAccount', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Exports rise by more than the extra income paid abroad, because taxes and domestic inputs stay in Iceland; the effect is small.', source: 'BPM6; CBI balance of payments commentary on aluminium' },
  { lever: 'aluminiumPrice', setting: 'max', variable: 'govBalance', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Higher smelter profits raise corporate tax.', source: 'Hagstofa THJ05132 (corporate tax)' },
  { lever: 'aluminiumPrice', setting: 'max', variable: 'unemployment', fromMonth: 1, toMonth: 12, sign: 0, theory: 'Capital-intensive smelters at capacity do not hire on a price change, and the windfall leaves the country, so jobs barely move.', source: 'Hagstofa THJ08420 (basic metals: small labour share); Eurostat bop_c6_a' },
  { lever: 'aluminiumPrice', setting: 'min', variable: 'dividendsAbroad', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Foreign owners absorb the smelters’ losses when the aluminium price falls.', source: 'Eurostat bop_c6_a; BPM6 ch. 11' },
  { lever: 'aluminiumPrice', setting: 'min', variable: 'currentAccount', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Lower export earnings, only partly offset by lower dividends abroad, worsen the current account a little.', source: 'BPM6; CBI balance of payments' },

  // ------------------------------------------------------------------------ lending appetite
  { lever: 'lendingAppetite', setting: 'up', variable: 'mortgageDebt', fromMonth: 3, toMonth: 240, sign: 1, theory: 'Endogenous money: more mortgage lending raises the stock of household mortgage debt relative to GDP.', source: 'McLeay, Radia and Thomas (2014), Bank of England Quarterly Bulletin Q1' },
  { lever: 'lendingAppetite', setting: 'up', variable: 'broadMoney', fromMonth: 3, toMonth: 120, sign: 1, theory: 'Loans create deposits: extra bank lending expands broad money.', source: 'McLeay, Radia and Thomas (2014); Keen (2011) Debunking Economics' },
  { lever: 'lendingAppetite', setting: 'up', variable: 'realHousePrice', fromMonth: 3, toMonth: 36, sign: 1, theory: 'A larger flow of mortgage credit bids up house prices.', source: 'Favara and Imbs (2015), American Economic Review; Keen’s credit accelerator' },
  { lever: 'lendingAppetite', setting: 'up', variable: 'consumption', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Debt-financed demand: part of new borrowing and housing-wealth gains is spent.', source: 'Mian and Sufi (2011), American Economic Review; Biggs, Mayer and Pick (2010)' },
  { lever: 'lendingAppetite', setting: 'up', variable: 'creditImpulse', fromMonth: 1, toMonth: 12, sign: 1, theory: 'A step up in the flow of net new credit is, by definition, a positive credit impulse on impact.', source: 'Biggs, Mayer and Pick (2010), ‘Credit and economic recovery’, DNB WP 218' },
  { lever: 'lendingAppetite', setting: 'up', variable: 'output', fromMonth: 3, toMonth: 36, sign: 1, theory: 'Credit-financed spending raises aggregate demand during the credit expansion.', source: 'Mian, Sufi and Verner (2017), Quarterly Journal of Economics' },
  { lever: 'lendingAppetite', setting: 'up', variable: 'currentAccount', fromMonth: 3, toMonth: 36, sign: -1, theory: 'Part of credit-financed demand leaks into imports, so the current account worsens during a credit boom.', source: 'Mendoza and Terrones (2008), NBER WP 14049' },
  { lever: 'lendingAppetite', setting: 'down', variable: 'realHousePrice', fromMonth: 3, toMonth: 36, sign: -1, theory: 'Less mortgage credit flowing into housing lowers house prices.', source: 'Favara and Imbs (2015), American Economic Review' },

  // ------------------------------------------------------------------------ debt-service cap
  { lever: 'dstiCap', setting: 'min', variable: 'mortgageDebt', fromMonth: 6, toMonth: 240, sign: -1, theory: 'A tighter debt-service-to-income cap limits new mortgage lending, so mortgage debt falls relative to baseline.', source: 'Kuttner and Shim (2016), Journal of Financial Stability' },
  { lever: 'dstiCap', setting: 'min', variable: 'realHousePrice', fromMonth: 3, toMonth: 36, sign: -1, theory: 'Borrower-based limits reduce credit-financed housing demand and house-price growth.', source: 'Kuttner and Shim (2016); Alam et al. (2019), IMF WP/19/66' },
  { lever: 'dstiCap', setting: 'min', variable: 'broadMoney', fromMonth: 6, toMonth: 120, sign: -1, theory: 'Less bank lending means fewer deposits are created.', source: 'McLeay, Radia and Thomas (2014), Bank of England Quarterly Bulletin' },
  { lever: 'dstiCap', setting: 'min', variable: 'consumption', fromMonth: 3, toMonth: 36, sign: -1, theory: 'Less credit-financed spending and lower housing wealth reduce consumption.', source: 'Mian and Sufi (2011); Richter, Schularick and Shim (2019), Journal of International Economics' },
  { lever: 'dstiCap', setting: 'down', variable: 'mortgageDebt', fromMonth: 12, toMonth: 60, sign: -1, theory: 'A moderate tightening binds for the tail of borrowers near the limit (first-time buyers), so lending and debt fall modestly. This failed at the vetting, before the cap was made distributional.', source: 'Kuttner and Shim (2016); Central Bank of Iceland Financial Stability reports on DSTI rules' },

  // -------------------------------------------------------------------------- loan-to-value cap
  // The lever's 'up' is now a loosening (80% is today's rule, 100 the most lenient); the vetting's
  // 25% cap is the lever's 'min' (50%) after credit-ltv-default-and-lever-semantics.
  { lever: 'ltvCap', setting: 'min', variable: 'mortgageDebt', fromMonth: 6, toMonth: 240, sign: -1, theory: 'A tight loan-to-value cap severely limits new purchase loans, so mortgage debt falls. This failed at the vetting, until the cap applied to gross lending.', source: 'Richter, Schularick and Shim (2019), Journal of International Economics; Cerutti, Claessens and Laeven (2017)' },
  { lever: 'ltvCap', setting: 'min', variable: 'realHousePrice', fromMonth: 3, toMonth: 36, sign: -1, theory: 'Tighter LTV limits reduce house-price growth by constraining leveraged demand.', source: 'Kuttner and Shim (2016); Alam et al. (2019), IMF WP/19/66' },
  { lever: 'ltvCap', setting: 'min', variable: 'broadMoney', fromMonth: 6, toMonth: 120, sign: -1, theory: 'Less mortgage origination by banks creates fewer deposits.', source: 'McLeay, Radia and Thomas (2014), Bank of England Quarterly Bulletin' },
  { lever: 'ltvCap', setting: 'min', variable: 'creditImpulse', fromMonth: 1, toMonth: 12, sign: -1, theory: 'Imposing a binding cap cuts the flow of net new credit on impact: a negative credit impulse.', source: 'Biggs, Mayer and Pick (2010), DNB WP 218' },
  { lever: 'ltvCap', setting: 'min', variable: 'consumption', fromMonth: 3, toMonth: 24, sign: -1, theory: 'Less credit-financed spending and lower housing wealth reduce consumption after a sharp LTV tightening.', source: 'Richter, Schularick and Shim (2019), Journal of International Economics' },

  // ------------------------------------------------------------ pension funds’ foreign share
  { lever: 'pfForeign', setting: 'up', variable: 'krona', fromMonth: 3, toMonth: 36, sign: -1, theory: 'Portfolio balance: pension funds sell krónur to buy foreign assets, so the króna weakens.', source: 'Kouri (1976); Branson (1977); CBI and pension funds’ March 2020 pause of FX purchases to support the króna' },
  { lever: 'pfForeign', setting: 'down', variable: 'krona', fromMonth: 3, toMonth: 36, sign: 1, theory: 'Repatriation means buying krónur, so the króna strengthens.', source: 'Kouri (1976); Branson (1977)' },
  { lever: 'pfForeign', setting: 'up', variable: 'inflation', fromMonth: 3, toMonth: 24, sign: 1, theory: 'Exchange-rate pass-through: a weaker króna raises import and consumer prices.', source: 'Central Bank of Iceland QMM documentation; Campa and Goldberg (2005), Review of Economics and Statistics' },
  { lever: 'pfForeign', setting: 'up', variable: 'currentAccount', fromMonth: 3, toMonth: 60, sign: 1, theory: 'Balance-of-payments identity: a private financial outflow is matched by a current-account surplus, through expenditure switching.', source: 'Godley and Lavoie (2007), Monetary Economics, ch. 12' },
  { lever: 'pfForeign', setting: 'up', variable: 'exports', fromMonth: 3, toMonth: 36, sign: 1, theory: 'A weaker real króna makes exports more competitive.', source: 'Marshall-Lerner and expenditure switching; Dornbusch (1976)' },
  { lever: 'pfForeign', setting: 'up', variable: 'imports', fromMonth: 3, toMonth: 36, sign: -1, theory: 'A weaker real króna makes imports dearer, so volumes fall.', source: 'Expenditure switching; Dornbusch (1976)' },
  { lever: 'pfForeign', setting: 'up', variable: 'pfForeignShare', fromMonth: 6, toMonth: 240, sign: 1, theory: 'Raising the target foreign share raises the actual foreign share as the funds rebalance.', source: 'Stock-flow portfolio adjustment (Tobin 1969)' },
  { lever: 'pfForeign', setting: 'up', mode: 'unlocked', variable: 'keyRate', fromMonth: 6, toMonth: 36, sign: 1, theory: 'An inflation-targeting central bank raises its rate against depreciation-driven inflation.', source: 'Taylor (1993); Central Bank of Iceland inflation-targeting framework' },

  // --------------------------------------------------------------------------- wage settlement
  { lever: 'wageSettlement', setting: 'max', variable: 'realWage', fromMonth: 1, toMonth: 12, sign: 1, theory: 'A nominal settlement raises the real wage on impact because prices are set as a markup on smoothed costs and catch up only with a lag (battle of markups).', source: 'Blanchard (1986), ‘The wage price spiral’, QJE; CBI Monetary Bulletin 2026/2 Box 2, ‘Wages +10%’' },
  { lever: 'wageSettlement', setting: 'max', variable: 'profitsFD', fromMonth: 1, toMonth: 6, sign: -1, theory: 'Profit squeeze: labour costs rise before prices, so margins compress first; profits are a residual and fall more than proportionally.', source: 'Goodwin (1967); first-round arithmetic on Hagstofa THJ08420 (2025) used in calibration.ts SRC.squeeze' },
  { lever: 'wageSettlement', setting: 'max', variable: 'profitsFX', fromMonth: 1, toMonth: 12, sign: -1, theory: 'Exporters are price-takers in world markets (main-course model), so higher wages cut their margins directly.', source: 'Aukrust (1977), the Norwegian main-course model; Carlin & Soskice (2015), Macroeconomics, ch. 11' },
  { lever: 'wageSettlement', setting: 'max', variable: 'inflation', fromMonth: 3, toMonth: 18, sign: 1, theory: 'Cost pass-through: higher unit labour costs raise domestic prices and CPI inflation within quarters.', source: 'CBI Monetary Bulletin 2026/2 Box 2; Bobeica, Ciccarelli & Vansteenkiste (2019), ECB WP 2235' },
  { lever: 'wageSettlement', setting: 'min', variable: 'priceLevel', fromMonth: 12, toMonth: 60, sign: -1, theory: 'Pass-through works both ways: a nominal wage cut lowers unit costs and, over time, the price level.', source: 'Daníelsson (2021), CBI research on CPI and unit labour costs moving together; Blanchard (1986)' },
  { lever: 'wageSettlement', setting: 'max', variable: 'unemployment', fromMonth: 3, toMonth: 24, sign: 1, theory: 'Labour demand falls when the real product wage rises; the labour market then does part of the work of restoring the wage share.', source: 'CBI DYNIMO results in MB 2026/2; Lichter, Peichl & Siegloch (2015), European Economic Review, meta-analysis of labour-demand elasticities' },
  { lever: 'wageSettlement', setting: 'max', mode: 'unlocked', variable: 'keyRate', fromMonth: 6, toMonth: 24, sign: 1, theory: 'An inflation-targeting central bank raises the policy rate in response to higher inflation and expectations (Taylor rule).', source: 'Taylor (1993); CBI MB 2026/2 ‘Wages +10%’: policy rate +1 to +1.5 pp at the peak' },
  { lever: 'wageSettlement', setting: 'max', variable: 'exports', fromMonth: 12, toMonth: 48, sign: -1, theory: 'Higher domestic costs appreciate the real exchange rate and erode export competitiveness.', source: 'Aukrust (1977); Carlin & Soskice (2015), open-economy wage-setting/price-setting model' },
  { lever: 'wageSettlement', setting: 'default', variable: 'priceLevel', fromMonth: 1, toMonth: 72, sign: 1, theory: 'A general pay rise is passed on to prices (battle of markups).', source: 'Blanchard (1986), Journal of Political Economy 94; CBI Monetary Bulletin 2026/2, Box 2' },
  { lever: 'wageSettlement', setting: 'default', variable: 'realWage', fromMonth: 1, toMonth: 12, sign: 1, theory: 'Nominal pay is set for the contract; prices catch up only gradually.', source: 'Bårdsen et al. (2005), The Econometrics of Macroeconomic Modelling' },

  // --------------------------------------------------- migration buffer and labour supply
  // The buffer acts only on job changes from the baseline, so most of its expectations are on top
  // of its companion shock (foreign demand −20%, src/harness/lever-headlines.ts).
  { lever: 'migration', setting: 'max', variable: 'unemployment', fromMonth: 1, toMonth: 240, sign: 0, theory: 'Plain runs (no companion). The buffer acts only on job changes from baseline; with no shock there is nothing to buffer and nothing should move.', source: 'Lever definition (labour-and-wages.ts); Blanchard & Katz (1992)' },
  { lever: 'migration', setting: 'max', withCompanion: true, variable: 'unemployment', fromMonth: 3, toMonth: 36, sign: -1, theory: 'On top of a 20% fall in foreign demand: when more of a job loss is met by workers leaving, unemployment rises less (migration as regional/national labour-market adjustment).', source: 'Blanchard & Katz (1992), BPEA; IMF (2026) Iceland Article IV on the flattened Beveridge curve' },
  { lever: 'migration', setting: 'min', withCompanion: true, variable: 'unemployment', fromMonth: 3, toMonth: 36, sign: 1, theory: 'On top of a 20% fall in foreign demand: with no migration response, every lost job adds to unemployment, so unemployment rises more than with the baseline buffer.', source: 'Blanchard & Katz (1992); Jauer, Liebig, Martin & Puhani (2019), Regional Studies' },
  { lever: 'migration', setting: 'max', withCompanion: true, variable: 'realWage', fromMonth: 12, toMonth: 60, sign: 1, theory: 'On top of a 20% fall in foreign demand: a smaller rise in unemployment means less slack in the wage Phillips curve, so real wages fall less.', source: 'Phillips (1958) and Blanchard & Katz (1999) wage curves; IMF (2026) Iceland Article IV' },
  { lever: 'migration', setting: 'min', withCompanion: true, variable: 'realWage', fromMonth: 12, toMonth: 60, sign: -1, theory: 'On top of a 20% fall in foreign demand: without a migration buffer the whole job loss becomes slack, so wage moderation is stronger.', source: 'Blanchard & Katz (1999), AER P&P, wage curves' },
  { lever: 'migration', setting: 'max', withCompanion: true, variable: 'govBalance', fromMonth: 1, toMonth: 12, sign: 1, theory: 'On top of a 20% fall in foreign demand: fewer residents are unemployed, so fewer benefits are paid (a smaller automatic-stabiliser outflow).', source: 'Horton & El-Ganainy (2009), IMF F&D ‘Automatic stabilizers’' },
  { lever: 'migration', setting: 'max', withCompanion: true, variable: 'realHousePrice', fromMonth: 12, toMonth: 60, sign: -1, theory: 'On top of a 20% fall in foreign demand: more emigration in a bust removes housing demand, so real house prices fall more. This failed at the vetting (LAB-4), before migrants carried housing demand.', source: 'Saiz (2007), Journal of Urban Economics; CBI Financial Stability reports on population growth and housing demand' },
  { lever: 'netImmigration', setting: 'default', variable: 'unemployment', fromMonth: 1, toMonth: 24, sign: 1, theory: 'A labour-supply shock raises unemployment until the newcomers are absorbed.', source: 'Borjas (1995), Journal of Economic Perspectives 9(2)' },
  { lever: 'netImmigration', setting: 'default', variable: 'realWage', fromMonth: 1, toMonth: 24, sign: -1, theory: 'More job-seekers slow wage growth (the wage Phillips curve).', source: 'Borjas (1995), Journal of Economic Perspectives 9(2)' },
  { lever: 'netImmigration', setting: 'default', variable: 'output', fromMonth: 60, toMonth: 240, sign: 1, theory: 'A lasting rise in the labour force raises output for good: newcomers work, earn and spend (a 2% larger labour force, about 1–2% more output). This failed at the re-vetting, while the newcomers left again (NETIMM-VANISHES).', source: 'Borjas (1995), Journal of Economic Perspectives 9(2); Ottaviano and Peri (2012), Journal of the European Economic Association 10(1); CBI Monetary Bulletin 2018 on immigration in 2017–19' },
  { lever: 'netImmigration', setting: 'default', variable: 'employment', fromMonth: 60, toMonth: 240, sign: 1, theory: 'Newcomers who stay find jobs as demand grows with them, so employment ends higher.', source: 'Ottaviano and Peri (2012), Journal of the European Economic Association 10(1)' },
  { lever: 'netImmigration', setting: 'default', variable: 'realHousePrice', fromMonth: 24, toMonth: 240, sign: 1, theory: 'More residents need homes, so a lasting rise in population raises house prices while supply adjusts.', source: 'Saiz (2007), Journal of Urban Economics 61(2)' },

  // ---------------------------------------------------------------------- unemployment benefits
  { lever: 'unemploymentBenefits', setting: 'max', variable: 'unemployment', fromMonth: 60, toMonth: 240, sign: 1, theory: 'A higher replacement rate lengthens job search and raises reservation wages, so equilibrium unemployment rises.', source: 'Layard, Nickell and Jackman (1991), Unemployment; Mortensen and Pissarides (1994)' },
  { lever: 'unemploymentBenefits', setting: 'up', variable: 'unemployment', fromMonth: 60, toMonth: 240, sign: 1, theory: 'A higher replacement rate lengthens job search and raises reservation wages, so equilibrium unemployment rises.', source: 'Layard, Nickell and Jackman (1991), Unemployment; Mortensen and Pissarides (1994)' },
  { lever: 'unemploymentBenefits', setting: 'min', variable: 'unemployment', fromMonth: 60, toMonth: 240, sign: -1, theory: 'Less generous benefits shorten job search, so equilibrium unemployment falls.', source: 'Layard, Nickell and Jackman (1991), Unemployment; Mortensen and Pissarides (1994)' },
  { lever: 'unemploymentBenefits', setting: 'max', mode: 'unlocked', variable: 'employment', fromMonth: 60, toMonth: 240, sign: -1, theory: 'A higher reservation wage raises the rate of unemployment at which inflation is steady, and an inflation-targeting central bank does not hold unemployment below it, so fewer people work. (With both policy levers locked, the key rate held, the benefits’ support to demand outweighs this: lever-vetting open item on benefits.)', source: 'Layard, Nickell and Jackman (1991), Unemployment; Mortensen and Pissarides (1994), Review of Economic Studies' },
  { lever: 'unemploymentBenefits', setting: 'max', mode: 'unlocked', variable: 'output', fromMonth: 120, toMonth: 240, sign: -1, theory: 'Fewer people in work produce less once policy has leaned against the higher normal unemployment.', source: 'Layard, Nickell and Jackman (1991), Unemployment' },

  // ------------------------------------------------- income tax held, the key rate held too (locked)
  { lever: 'incomeTax', setting: 'up', mode: 'locked', variable: 'output', fromMonth: 6, toMonth: 60, sign: -1, theory: 'Tax multiplier: a higher income-tax rate cuts disposable income and consumption, and output follows through the multiplier.', source: 'Romer and Romer (2010, AER); Mertens and Ravn (2013, AER); IMF WEO Oct 2010 ch. 3' },
  { lever: 'incomeTax', setting: 'down', mode: 'locked', variable: 'output', fromMonth: 6, toMonth: 60, sign: 1, theory: 'Tax multiplier, symmetric: a tax cut raises disposable income, consumption and output.', source: 'Romer and Romer (2010, AER); Guajardo, Leigh and Pescatori (2014, JEEA)' },
  { lever: 'incomeTax', setting: 'up', mode: 'locked', variable: 'consumption', fromMonth: 1, toMonth: 60, sign: -1, theory: 'Consumption function: spending falls with after-tax income, gradually because of habit.', source: 'Parker, Souleles, Johnson and McClelland (2013, AER); Cloyne (2013, AER)' },
  { lever: 'incomeTax', setting: 'up', mode: 'locked', variable: 'realDisposableIncome', fromMonth: 1, toMonth: 60, sign: -1, theory: 'Arithmetic: disposable income is gross income minus tax.', source: 'SNA 2008 household income account' },
  { lever: 'incomeTax', setting: 'up', mode: 'locked', variable: 'govBalance', fromMonth: 1, toMonth: 60, sign: 1, theory: 'Budget arithmetic: automatic stabilisers win back only part of a tax rise (budget semi-elasticity about 0.4–0.5).', source: 'Price, Dang and Botev (2015), OECD Economics Department WP 1275' },
  { lever: 'incomeTax', setting: 'up', mode: 'locked', variable: 'govDebt', fromMonth: 12, toMonth: 60, sign: -1, theory: 'Government budget constraint: surpluses repay debt.', source: 'Bohn (1998, QJE); Godley and Lavoie (2007) ch. 3' },
  { lever: 'incomeTax', setting: 'up', mode: 'locked', variable: 'currentAccount', fromMonth: 3, toMonth: 36, sign: 1, theory: 'Sectoral balances and twin deficits: fiscal tightening lowers import demand and improves the current account.', source: 'Godley (1999, Levy Institute); Abbas, Bouhga-Hagbe, Fatás, Mauro and Velloso (2011, IMF Economic Review)' },
  { lever: 'incomeTax', setting: 'max', mode: 'locked', variable: 'keyRate', fromMonth: 1, toMonth: 240, sign: 0, theory: 'A locked POLICY lever never moves unless the user moves it. The Taylor rule only suggests.', source: 'Decisions 0004 and 0010 (model rule 11)' },
  { lever: 'incomeTax', setting: 'max', mode: 'key rate locked', variable: 'keyRate', fromMonth: 1, toMonth: 240, sign: 0, theory: 'With the key rate locked, the central bank’s rule only suggests, whatever the budget does.', source: 'Decision 0010 (model rule 11)' },
  { lever: 'incomeTax', setting: 'up', mode: 'locked', variable: 'consumption', fromMonth: 1, toMonth: 24, sign: -1, theory: 'A higher income tax cuts disposable income and so spending (with a cash buffer, gradually).', source: 'Godley and Lavoie (2007), Monetary Economics, ch. 3' },

  // ---------------------------------------------------- income tax held, the key rate acting (unlocked)
  // Until padlocks (decision 0010) these were expectations on an offset added to the debt rule; they
  // are now on locking income tax higher or lower while the central bank's rule acts. The debt rule
  // no longer gives the rise back while the lever is held, so the debt expectation keeps its sign
  // over the same window for a simpler reason: the surplus lasts.
  { lever: 'incomeTax', setting: 'up', mode: 'unlocked', variable: 'output', fromMonth: 3, toMonth: 36, sign: -1, theory: 'Tax multiplier, damped by the central bank easing in response.', source: 'IMF WEO Oct 2010 ch. 3; Batini, Eyraud, Forni and Weber (2014, IMF TNM/14/04)' },
  { lever: 'incomeTax', setting: 'down', mode: 'unlocked', variable: 'output', fromMonth: 3, toMonth: 36, sign: 1, theory: 'Tax multiplier, symmetric, damped by monetary tightening.', source: 'IMF WEO Oct 2010 ch. 3' },
  { lever: 'incomeTax', setting: 'up', mode: 'unlocked', variable: 'keyRate', fromMonth: 6, toMonth: 36, sign: -1, theory: 'Taylor rule: fiscal tightening lowers inflation and the output gap, so the rule cuts the key rate.', source: 'Taylor (1993, Carnegie-Rochester)' },
  { lever: 'incomeTax', setting: 'down', mode: 'unlocked', variable: 'keyRate', fromMonth: 6, toMonth: 36, sign: 1, theory: 'Taylor rule leans against a fiscal stimulus.', source: 'Taylor (1993); Leeper (1991, JME), policy interaction' },
  { lever: 'incomeTax', setting: 'up', mode: 'unlocked', variable: 'govBalance', fromMonth: 1, toMonth: 36, sign: 1, theory: 'Budget arithmetic: a higher tax rate raises revenue, and stabilisers only partly offset it.', source: 'Price, Dang and Botev (2015), OECD WP 1275' },
  { lever: 'incomeTax', setting: 'up', mode: 'unlocked', variable: 'govDebt', fromMonth: 12, toMonth: 120, sign: -1, theory: 'Government budget constraint: surpluses reduce debt.', source: 'Bohn (1998, QJE)' },
  { lever: 'incomeTax', setting: 'up', mode: 'unlocked', variable: 'realDisposableIncome', fromMonth: 1, toMonth: 36, sign: -1, theory: 'Arithmetic: higher tax means lower disposable income.', source: 'SNA 2008 household income account' },

  // ------------------------------------------------------------------------------------ VAT
  { lever: 'vat', setting: 'up', variable: 'priceLevel', fromMonth: 1, toMonth: 12, sign: 1, theory: 'VAT pass-through: a higher consumption tax raises consumer prices, almost fully for standard-rate changes; a lasting rise moves the price level once.', source: 'Benedek, De Mooij, Keen and Wingender (2020), International Tax and Public Finance 27' },
  { lever: 'vat', setting: 'down', variable: 'priceLevel', fromMonth: 1, toMonth: 12, sign: -1, theory: 'VAT pass-through of a cut, which may be slower than for a rise.', source: 'Benedek et al. (2020); Benzarti, Carloni, Harju and Kosonen (2020, JPE)' },
  { lever: 'vat', setting: 'up', variable: 'realWage', fromMonth: 1, toMonth: 36, sign: -1, theory: 'Incidence: a broad consumption tax lowers the real consumer wage (W ÷ CPI). Its burden falls on real factor incomes.', source: 'Atkinson and Stiglitz (1980), Lectures on Public Economics ch. 6; Fullerton and Metcalf (2002), Handbook of Public Economics' },
  { lever: 'vat', setting: 'up', variable: 'consumption', fromMonth: 1, toMonth: 36, sign: -1, theory: 'Higher consumer prices cut real purchasing power and real consumption.', source: 'Crossley, Low and Wakefield (2009, Fiscal Studies), UK VAT cut; Cashin and Unayama (2016, REStat), Japan' },
  { lever: 'vat', setting: 'up', variable: 'govBalance', fromMonth: 6, toMonth: 36, sign: 1, theory: 'Budget arithmetic: more VAT revenue, only partly offset by a smaller base. From m6 so the one-off indexation accrual has passed.', source: 'Keen and Lockwood (2010, JDE); ESA 2010 §4.47' },
  { lever: 'vat', setting: 'up', variable: 'mortgageDebt', fromMonth: 1, toMonth: 6, sign: 1, theory: 'CPI indexation: most Icelandic mortgages are indexed, so a price-level rise adds to their principal.', source: 'Central Bank of Iceland, Financial Stability (2024); Act 38/2001 on interest and indexation' },
  { lever: 'vat', setting: 'up', mode: 'locked', variable: 'keyRate', fromMonth: 1, toMonth: 240, sign: 0, theory: 'A locked POLICY lever never moves unless the user moves it.', source: 'docs/decisions/0004-stabilisers.md (model rule 11)' },
  { lever: 'vat', setting: 'up', variable: 'output', fromMonth: 1, toMonth: 36, sign: -1, theory: 'A tax increase lowers real disposable income and demand (tax multiplier).', source: 'IMF WEO Oct 2010 ch. 3; Coenen et al. (2012, AEJ: Macro)' },

  // ------------------------------------------------------------------ public services: health
  { lever: 'health', setting: 'max', variable: 'output', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Government purchases add directly to demand and output (Keynesian multiplier).', source: 'Blanchard and Perotti (2002, QJE); Ramey (2019, JEP)' },
  { lever: 'health', setting: 'min', variable: 'output', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Cutting government purchases lowers demand and output.', source: 'Blanchard and Perotti (2002); Guajardo, Leigh and Pescatori (2014, JEEA)' },
  { lever: 'health', setting: 'up', variable: 'unemployment', fromMonth: 1, toMonth: 24, sign: -1, theory: 'More public staff and higher output raise employment (Okun’s law).', source: 'Okun (1962)' },
  { lever: 'health', setting: 'max', variable: 'govBalance', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Higher spending worsens the budget balance, only partly offset by extra tax revenue.', source: 'Government budget identity; Girouard and André (2005, OECD WP 434)' },
  { lever: 'health', setting: 'max', variable: 'imports', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Import leakage: part of public purchases and of the extra income is spent on imports.', source: 'Batini et al. (2014, IMF TNM); Statistics Iceland (imports about 43% of GDP)' },
  { lever: 'health', setting: 'max', mode: 'unlocked', variable: 'keyRate', fromMonth: 3, toMonth: 36, sign: 1, theory: 'An inflation-targeting central bank leans against a demand expansion (Taylor rule).', source: 'Taylor (1993)' },
  { lever: 'health', setting: 'max', variable: 'govDebt', fromMonth: 12, toMonth: 60, sign: 1, theory: 'Persistent deficits accumulate into debt (government budget constraint).', source: 'Blanchard, Macroeconomics, ch. 22' },
  { lever: 'health', setting: 'max', mode: 'locked', variable: 'inflation', fromMonth: 6, toMonth: 36, sign: 1, theory: 'With the policy rate held, a tighter labour market raises wage and price inflation (Phillips curve).', source: 'Phillips (1958); Blanchard, Cerutti and Summers (2015)' },

  // --------------------------------------------------------------- public services: education
  { lever: 'education', setting: 'max', variable: 'output', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Government purchases add directly to demand and output.', source: 'Blanchard and Perotti (2002); Ramey (2019)' },
  { lever: 'education', setting: 'min', variable: 'output', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Cutting government purchases lowers demand and output.', source: 'Guajardo, Leigh and Pescatori (2014)' },
  { lever: 'education', setting: 'up', variable: 'unemployment', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Labour-intensive public services hire staff directly; higher output raises jobs (Okun’s law).', source: 'Okun (1962)' },
  { lever: 'education', setting: 'max', variable: 'govBalance', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Higher spending worsens the budget balance.', source: 'Government budget identity' },
  { lever: 'education', setting: 'max', mode: 'unlocked', variable: 'keyRate', fromMonth: 3, toMonth: 36, sign: 1, theory: 'The Taylor rule leans against a demand expansion.', source: 'Taylor (1993)' },
  { lever: 'education', setting: 'max', mode: 'locked', variable: 'inflation', fromMonth: 6, toMonth: 36, sign: 1, theory: 'With the policy rate held, a tighter labour market raises inflation (Phillips curve).', source: 'Phillips (1958)' },

  // ------------------------------------------------------------ public services: other services
  { lever: 'otherServices', setting: 'max', variable: 'output', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Government purchases add directly to demand and output.', source: 'Blanchard and Perotti (2002); Ramey (2019)' },
  { lever: 'otherServices', setting: 'min', variable: 'output', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Cutting government purchases lowers demand and output.', source: 'Guajardo, Leigh and Pescatori (2014)' },
  { lever: 'otherServices', setting: 'up', variable: 'unemployment', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Higher public spending raises employment (Okun’s law).', source: 'Okun (1962)' },
  { lever: 'otherServices', setting: 'max', variable: 'govBalance', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Higher spending worsens the budget balance.', source: 'Government budget identity' },
  { lever: 'otherServices', setting: 'max', variable: 'imports', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Import leakage from purchases and from the extra income.', source: 'Batini et al. (2014)' },
  { lever: 'otherServices', setting: 'max', mode: 'unlocked', variable: 'keyRate', fromMonth: 3, toMonth: 36, sign: 1, theory: 'The Taylor rule leans against a demand expansion.', source: 'Taylor (1993)' },

  // --------------------------------------------------------------------------- public investment
  { lever: 'publicInvestment', setting: 'max', variable: 'output', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Public investment raises demand; its domestic content raises output at once.', source: 'IMF WEO Oct 2014, ch. 3 (Abiad et al. 2016)' },
  { lever: 'publicInvestment', setting: 'min', variable: 'output', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Cutting public investment lowers demand and output.', source: 'IMF WEO Oct 2014, ch. 3' },
  { lever: 'publicInvestment', setting: 'max', variable: 'investment', fromMonth: 1, toMonth: 60, sign: 1, theory: 'Public investment is part of gross fixed capital formation.', source: 'SNA 2008 national-accounts identity' },
  { lever: 'publicInvestment', setting: 'max', variable: 'imports', fromMonth: 1, toMonth: 12, sign: 1, theory: 'Investment goods have high import content in a small open economy.', source: 'OECD TiVA (import content of investment)' },
  { lever: 'publicInvestment', setting: 'max', variable: 'currentAccount', fromMonth: 1, toMonth: 12, sign: -1, theory: 'Sectoral balances: a larger public deficit with extra imports worsens the current account (twin deficits).', source: 'Godley and Lavoie (2007); Abbas et al. (2011, IMF Econ Review)' },
  { lever: 'publicInvestment', setting: 'max', variable: 'govBalance', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Higher spending worsens the budget balance.', source: 'Government budget identity' },
  { lever: 'publicInvestment', setting: 'max', mode: 'unlocked', variable: 'keyRate', fromMonth: 3, toMonth: 36, sign: 1, theory: 'The Taylor rule leans against a demand expansion.', source: 'Taylor (1993)' },
  { lever: 'publicInvestment', setting: 'up', variable: 'unemployment', fromMonth: 3, toMonth: 36, sign: -1, theory: 'Construction output raises employment with a lag (Okun’s law).', source: 'Okun (1962); IMF WEO Oct 2014, ch. 3' },

  // ---------------------------------------------------------------------------- old-age transfers
  { lever: 'oldAgeTransfers', setting: 'max', variable: 'consumption', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Transfers raise recipients’ disposable income, and they spend part of it (MPC).', source: 'Parker, Souleles, Johnson and McClelland (2013, AER); Wilcox (1989, JPE)' },
  { lever: 'oldAgeTransfers', setting: 'min', variable: 'consumption', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Cutting transfers lowers recipients’ income and spending.', source: 'Parker et al. (2013)' },
  { lever: 'oldAgeTransfers', setting: 'max', variable: 'realDisposableIncome', fromMonth: 1, toMonth: 12, sign: 1, theory: 'A transfer is household income: disposable income rises by the after-tax amount.', source: 'SNA 2008 household income account' },
  { lever: 'oldAgeTransfers', setting: 'max', variable: 'output', fromMonth: 3, toMonth: 24, sign: 1, theory: 'The transfer multiplier: extra spending by recipients raises output, by less than purchases do.', source: 'Coenen et al. (2012, AEJ Macro)' },
  { lever: 'oldAgeTransfers', setting: 'max', variable: 'govBalance', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Higher transfers worsen the budget balance.', source: 'Government budget identity' },
  { lever: 'oldAgeTransfers', setting: 'max', variable: 'govDebt', fromMonth: 12, toMonth: 60, sign: 1, theory: 'Persistent deficits accumulate into debt.', source: 'Government budget constraint' },
  { lever: 'oldAgeTransfers', setting: 'max', mode: 'unlocked', variable: 'keyRate', fromMonth: 6, toMonth: 36, sign: 1, theory: 'The Taylor rule leans against the rise in demand.', source: 'Taylor (1993)' },

  // ------------------------------------------------------------------------------ family benefits
  { lever: 'familyBenefits', setting: 'max', variable: 'consumption', fromMonth: 1, toMonth: 24, sign: 1, theory: 'Benefits to young families (high MPC, often liquidity-constrained) raise their spending.', source: 'Parker et al. (2013); Kaplan and Violante (2014, Econometrica)' },
  { lever: 'familyBenefits', setting: 'min', variable: 'consumption', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Cutting benefits lowers recipients’ income and spending.', source: 'Parker et al. (2013)' },
  { lever: 'familyBenefits', setting: 'max', variable: 'realDisposableIncome', fromMonth: 1, toMonth: 12, sign: 1, theory: 'A transfer is household income.', source: 'SNA 2008 household income account' },
  { lever: 'familyBenefits', setting: 'max', variable: 'output', fromMonth: 3, toMonth: 24, sign: 1, theory: 'Transfer multiplier through recipients’ spending.', source: 'Coenen et al. (2012)' },
  { lever: 'familyBenefits', setting: 'max', variable: 'govBalance', fromMonth: 1, toMonth: 24, sign: -1, theory: 'Higher transfers worsen the budget balance.', source: 'Government budget identity' },
  { lever: 'familyBenefits', setting: 'max', variable: 'govDebt', fromMonth: 12, toMonth: 60, sign: 1, theory: 'Persistent deficits accumulate into debt.', source: 'Government budget constraint' },
  { lever: 'familyBenefits', setting: 'max', mode: 'unlocked', variable: 'keyRate', fromMonth: 6, toMonth: 36, sign: 1, theory: 'The Taylor rule leans against the rise in demand.', source: 'Taylor (1993)' },

  // --------------------------------------------------------------------------------- bond buyers
  // A choice: 1 banks, 2 the central bank, 3 pension funds, 4 older households, each against the
  // default mix, on top of the companion deficit (public investment +2% of GDP).
  { lever: 'bondBuyers', setting: 1, withCompanion: true, variable: 'broadMoney', fromMonth: 1, toMonth: 60, sign: 1, theory: 'When banks buy the new bonds, the deposits the government spends are not drained, so broad money rises compared with the 40/60 mix.', source: 'McLeay, Radia and Thomas (2014, BoE Quarterly Bulletin Q1); Godley and Lavoie (2007)' },
  { lever: 'bondBuyers', setting: 2, withCompanion: true, variable: 'broadMoney', fromMonth: 1, toMonth: 60, sign: 1, theory: 'Central-bank purchases create reserves, and the spent deposits stay in the economy, as under QE.', source: 'McLeay, Radia and Thomas (2014)' },
  { lever: 'bondBuyers', setting: 3, withCompanion: true, variable: 'broadMoney', fromMonth: 1, toMonth: 60, sign: -1, theory: 'Non-bank buyers pay with existing deposits, which drains the money the deficit adds. Broad money is lower than under the mix, where banks take 40%.', source: 'McLeay, Radia and Thomas (2014); Godley and Lavoie (2007)' },
  { lever: 'bondBuyers', setting: 4, withCompanion: true, variable: 'broadMoney', fromMonth: 1, toMonth: 60, sign: -1, theory: 'Households pay with existing deposits: money moves rather than being created.', source: 'McLeay, Radia and Thomas (2014)' },
  { lever: 'bondBuyers', setting: 2, withCompanion: true, variable: 'govDebt', fromMonth: 24, toMonth: 240, sign: -1, theory: 'Interest on central-bank-held bonds returns to the Treasury as central-bank profit (consolidation), so deficits and debt are lower.', source: 'Buiter (2007, ‘Seigniorage’, Economics e-journal)' },
  { lever: 'bondBuyers', setting: 1, withCompanion: true, variable: 'output', fromMonth: 1, toMonth: 24, sign: 0, theory: 'When the central bank sets the interest rate, who holds the bonds changes money but not the cost of credit, so demand is essentially unchanged in the short run.', source: 'McLeay, Radia and Thomas (2014); Borio and Disyatat (2010, BIS WP 292)' },
];
