/**
 * Reference economy: the charts (indicators) and the narration feed.
 *
 * Indicators are computed from variables and stocks and shown as deviations from the
 * baseline. Feed rules only narrate; they never change the model.
 */
import type { ModuleDef } from '../../core/types.ts';

export const indicators: ModuleDef = {
  id: 'indicators',
  label: 'Charts and feed',
  description: 'The eight headline charts and the messages that narrate them.',
  requires: ['structure', 'demand', 'labour-and-prices', 'central-bank', 'banking-and-credit', 'government'],
  indicators: [
    {
      id: 'output',
      label: 'Output (real GDP)',
      group: 'Overview',
      unit: '% vs baseline',
      display: 'deviation-pct',
      compute: (c) => c.v('output'),
      description: 'Everything produced in a year, at baseline prices.',
      drivers: ['output', 'consumption', 'investmentReal', 'govSpending'],
      concepts: ['multiplier', 'steady-state-baseline'],
    },
    {
      id: 'inflation',
      label: 'Inflation (12 months)',
      group: 'Overview',
      unit: 'pp vs baseline',
      display: 'deviation-pp',
      compute: (c) => c.v('inflation12'),
      description: 'How much prices rose over the past year. The baseline has zero inflation.',
      drivers: ['inflation12', 'price', 'wage'],
      concepts: ['markup-pricing', 'cost-pass-through'],
    },
    {
      id: 'keyRate',
      label: 'Key interest rate',
      group: 'Overview',
      unit: 'pp vs baseline',
      display: 'deviation-pp',
      compute: (c) => c.v('keyRate'),
      description: 'The central bank’s policy rate.',
      drivers: ['keyRate'],
      concepts: ['taylor-rule'],
    },
    {
      id: 'unemployment',
      label: 'Unemployment rate',
      group: 'Overview',
      unit: 'pp vs baseline',
      display: 'deviation-pp',
      compute: (c) => c.v('unemployment'),
      description: 'Share of the labour force without a job.',
      drivers: ['unemployment', 'employment'],
      concepts: ['okun-law'],
    },
    {
      id: 'broadMoney',
      label: 'Broad money',
      group: 'Money and credit',
      unit: '% vs baseline',
      display: 'deviation-pct',
      compute: (c) => c.stock('deposits', 'HH') + c.stock('deposits', 'F'),
      description: 'Deposits of households and firms. No formula sets it: it is whatever lending, repayments, taxes and spending leave in deposit accounts.',
      drivers: ['newLoans', 'loanRepayments', 'bondIssue'],
      concepts: ['endogenous-money', 'money-destruction', 'double-entry'],
    },
    {
      id: 'creditImpulse',
      label: 'Credit impulse',
      group: 'Money and credit',
      unit: 'pp of GDP',
      display: 'deviation',
      compute: (c) => c.v('creditImpulse'),
      description: 'Change in the yearly flow of new credit compared with a year earlier.',
      drivers: ['creditImpulse', 'netLending'],
      concepts: ['credit-impulse'],
    },
    {
      id: 'privateDebt',
      label: 'Private debt',
      group: 'Money and credit',
      unit: 'pp of GDP',
      display: 'deviation',
      compute: (c) => (100 * c.stock('loans', 'F')) / c.v('gdp'),
      description: 'Firms’ bank loans, as % of a year’s GDP.',
      drivers: ['newLoans', 'loanRepayments', 'gdp'],
      concepts: ['endogenous-money'],
    },
    {
      id: 'govDebt',
      label: 'Government debt',
      group: 'Government',
      unit: 'pp of GDP',
      display: 'deviation',
      compute: (c) => (100 * c.stock('bonds', 'G')) / c.v('gdp'),
      description: 'Government bonds outstanding, as % of a year’s GDP.',
      drivers: ['bondIssue', 'deficit', 'gdp'],
      concepts: ['deficits-and-money', 'sectoral-balances'],
    },
  ],
  feed: [
    { id: 'rateUp', indicator: 'keyRate', above: 0.25, message: 'The central bank raises its key rate', concept: 'taylor-rule' },
    { id: 'rateDown', indicator: 'keyRate', below: -0.25, message: 'The central bank cuts its key rate', concept: 'taylor-rule' },
    { id: 'inflationUp', indicator: 'inflation', above: 0.5, message: 'Inflation picks up as higher costs pass through to prices', concept: 'cost-pass-through' },
    { id: 'jobsLost', indicator: 'unemployment', above: 0.3, message: 'Unemployment rises as firms need fewer workers', concept: 'okun-law' },
    { id: 'moneyUp', indicator: 'broadMoney', above: 1, message: 'Broad money grows: new loans and deficits create deposits', concept: 'endogenous-money' },
    { id: 'moneyDown', indicator: 'broadMoney', below: -1, message: 'Broad money shrinks as loans are repaid', concept: 'money-destruction' },
    { id: 'creditUp', indicator: 'creditImpulse', above: 0.1, message: 'Credit is accelerating: the credit impulse turns positive', concept: 'credit-impulse' },
    { id: 'creditDown', indicator: 'creditImpulse', below: -0.1, message: 'Credit is slowing: the credit impulse turns negative', concept: 'credit-impulse' },
  ],
};
