/**
 * Reference economy: the players and the instruments they hold.
 *
 * Five players, each with a way of paying (settlement), and six instruments: five financial
 * claims (someone's asset and someone else's liability) and one real asset.
 */
import type { ModuleDef } from '../../core/types.ts';

export const structure: ModuleDef = {
  id: 'structure',
  label: 'Players and instruments',
  description: 'Households, firms, one bank, the central bank and the government, with the claims that connect them.',
  players: [
    {
      id: 'HH',
      label: 'Households',
      short: 'HH',
      group: 'Households',
      color: '#3A87C8',
      description: 'Everyone in their role as workers, consumers, savers and owners of firms and the bank.',
      settlement: 'deposits',
      layout: { x: 0.12, y: 0.5 },
    },
    {
      id: 'F',
      label: 'Firms',
      short: 'F',
      group: 'Firms',
      color: '#E69F00',
      description: 'All businesses: they hire workers, sell goods and services, invest and borrow from the bank.',
      settlement: 'deposits',
      layout: { x: 0.48, y: 0.18 },
    },
    {
      id: 'B',
      label: 'Bank',
      short: 'B',
      group: 'Banks',
      color: '#009E73',
      description: 'All banks as one. It keeps everyone’s deposits, lends to firms and holds government bonds.',
      settlement: 'bank',
      layout: { x: 0.48, y: 0.82 },
    },
    {
      id: 'CB',
      label: 'Central bank',
      short: 'CB',
      group: 'Central bank',
      color: '#CC79A7',
      description: 'Sets the key interest rate, keeps the bank’s reserves and the government’s account.',
      settlement: 'central-bank',
      layout: { x: 0.86, y: 0.76 },
    },
    {
      id: 'G',
      label: 'Government',
      short: 'G',
      group: 'Government',
      color: '#8C8C8C',
      description: 'Buys goods and services, taxes household income and borrows by selling bonds.',
      settlement: 'treasury',
      layout: { x: 0.86, y: 0.24 },
    },
  ],
  instruments: [
    {
      id: 'deposits',
      label: 'Bank deposits',
      kind: 'financial',
      issuers: ['B'],
      holders: ['HH', 'F'],
      valuation: 'nominal',
      description: 'Money as most people know it: a claim on the bank. Created when the bank lends or pays, destroyed when it is repaid.',
      concepts: ['endogenous-money'],
    },
    {
      id: 'reserves',
      label: 'Reserves',
      kind: 'financial',
      issuers: ['CB'],
      holders: ['B'],
      valuation: 'nominal',
      description: 'The bank’s account at the central bank. Payments to and from the state move reserves.',
      concepts: ['reserves-and-payments'],
    },
    {
      id: 'treasuryAccount',
      label: 'Treasury account',
      kind: 'financial',
      issuers: ['CB'],
      holders: ['G'],
      valuation: 'nominal',
      description: 'The government’s account at the central bank, from which it pays and into which taxes arrive.',
      concepts: ['reserves-and-payments'],
    },
    {
      id: 'loans',
      label: 'Business loans',
      kind: 'financial',
      issuers: ['F'],
      holders: ['B'],
      valuation: 'nominal',
      description: 'What firms owe the bank. Each new loan creates a deposit; each repayment destroys one.',
      concepts: ['endogenous-money', 'money-destruction'],
    },
    {
      id: 'bonds',
      label: 'Government bonds',
      kind: 'financial',
      issuers: ['G'],
      holders: ['B', 'CB'],
      valuation: 'nominal',
      description: 'What the government owes. Held by the bank and the central bank, so the deficits they finance add to money.',
      concepts: ['deficits-and-money'],
    },
    {
      id: 'capital',
      label: 'Machines and buildings',
      kind: 'real',
      issuers: [],
      holders: ['F'],
      valuation: 'at-cost',
      description: 'The firms’ capital stock, valued at what it cost. Investment adds to it; wear and tear (depreciation) reduces it.',
      concepts: ['net-worth'],
    },
  ],
};
